import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { eq } from 'drizzle-orm';
import { describe, expect, it } from 'vitest';
import { initializeDatabaseSchema } from '@/db/bootstrap';
import * as schema from '@/db/schema';
import { createEconomyService } from '@/lib/economy-service';

function createTestDatabase() {
  const sqlite = new Database(':memory:');
  initializeDatabaseSchema(sqlite);
  return {
    sqlite,
    db: drizzle(sqlite, { schema }),
  };
}

describe('createEconomyService.advanceGameTurn', () => {
  it('advances Winter into Spring of the next year through the canonical resolver', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-winter',
      name: 'Winter Test',
      gmCode: 'gm-winter',
      playerCode: 'player-winter',
      currentYear: 3,
      currentSeason: 'Winter',
      turnPhase: 'Submission',
    }).run();

    db.insert(schema.realms).values({
      id: 'realm-winter',
      gameId: 'game-winter',
      name: 'Frosthold',
      governmentType: 'Monarch',
      treasury: 1000,
      taxType: 'Tribute',
    }).run();

    db.insert(schema.territories).values({
      id: 'territory-winter',
      gameId: 'game-winter',
      name: 'Frost Vale',
      realmId: 'realm-winter',
    }).run();

    db.insert(schema.settlements).values({
      id: 'settlement-winter',
      territoryId: 'territory-winter',
      realmId: 'realm-winter',
      name: 'Frosthold',
      size: 'Village',
    }).run();

    const result = service.advanceGameTurn('game-winter', {
      expectedYear: 3,
      expectedSeason: 'Winter',
      idempotencyKey: 'game-winter:3:Winter',
    });

    expect(result).toMatchObject({
      resolvedYear: 3,
      resolvedSeason: 'Winter',
      year: 4,
      season: 'Spring',
      replayed: false,
    });

    sqlite.close();
  });

  it('resolves a full seasonal transition transactionally and replays idempotently', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-1',
      name: 'Economy Test',
      gmCode: 'gm-code',
      playerCode: 'player-code',
      currentYear: 2,
      currentSeason: 'Spring',
      turnPhase: 'Submission',
    }).run();

    db.insert(schema.realms).values([
      {
        id: 'realm-a',
        gameId: 'game-1',
        name: 'Aster',
        governmentType: 'Monarch',
        treasury: 10000,
        taxType: 'Tribute',
        consecutiveFoodShortageSeasons: 1,
        consecutiveFoodRecoverySeasons: 0,
        turmoilSources: JSON.stringify([
          {
            id: 'ts-seasonal',
            kind: 'gm_event',
            description: 'Seasonal pressure',
            amount: 2,
            durationType: 'seasonal',
            seasonsRemaining: 2,
            originYear: 2,
            originSeason: 'Spring',
            linkedEntityType: 'event',
            linkedEntityId: 'ts-seasonal',
            autoGenerated: true,
            notes: null,
          },
        ]),
      },
      {
        id: 'realm-b',
        gameId: 'game-1',
        name: 'Bastion',
        governmentType: 'Council',
        treasury: 6000,
        taxType: 'Tribute',
      },
    ]).run();

    db.insert(schema.territories).values([
      {
        id: 'territory-a',
        gameId: 'game-1',
        name: 'Aster Vale',
        realmId: 'realm-a',
      },
      {
        id: 'territory-b',
        gameId: 'game-1',
        name: 'Bastion Reach',
        realmId: 'realm-b',
      },
    ]).run();

    db.insert(schema.settlements).values([
      {
        id: 'settlement-a',
        territoryId: 'territory-a',
        realmId: 'realm-a',
        name: 'Aster Keep',
        size: 'Village',
      },
      {
        id: 'settlement-b',
        territoryId: 'territory-b',
        realmId: 'realm-b',
        name: 'Bastion Port',
        size: 'Village',
      },
    ]).run();

    db.insert(schema.buildings).values([
      {
        id: 'building-a-1',
        settlementId: 'settlement-a',
        locationType: 'settlement',
        type: 'Theatre',
        category: 'Civic',
        size: 'Medium',
        takesBuildingSlot: true,
        isOperational: false,
        maintenanceState: 'active',
        constructionTurnsRemaining: 1,
      },
      {
        id: 'building-a-2',
        settlementId: 'settlement-a',
        locationType: 'settlement',
        type: 'Theatre',
        category: 'Civic',
        size: 'Medium',
        takesBuildingSlot: true,
        isOperational: false,
        maintenanceState: 'active',
        constructionTurnsRemaining: 2,
      },
      {
        id: 'building-a-3',
        settlementId: 'settlement-a',
        locationType: 'settlement',
        type: 'Theatre',
        category: 'Civic',
        size: 'Medium',
        takesBuildingSlot: true,
        isOperational: false,
        maintenanceState: 'active',
        constructionTurnsRemaining: 2,
      },
      {
        id: 'building-a-4',
        settlementId: 'settlement-a',
        locationType: 'settlement',
        type: 'Theatre',
        category: 'Civic',
        size: 'Medium',
        takesBuildingSlot: true,
        isOperational: false,
        maintenanceState: 'active',
        constructionTurnsRemaining: 2,
      },
    ]).run();

    db.insert(schema.resourceSites).values([
      {
        id: 'resource-a',
        territoryId: 'territory-a',
        settlementId: 'settlement-a',
        resourceType: 'Timber',
        rarity: 'Common',
      },
      {
        id: 'resource-b',
        territoryId: 'territory-b',
        settlementId: 'settlement-b',
        resourceType: 'Gold',
        rarity: 'Luxury',
      },
    ]).run();

    db.insert(schema.troops).values({
      id: 'troop-a-1',
      realmId: 'realm-a',
      type: 'Spearmen',
      class: 'Basic',
      armourType: 'Light',
      condition: 'Healthy',
      recruitmentTurnsRemaining: 1,
      garrisonSettlementId: 'settlement-a',
    }).run();

    db.insert(schema.tradeRoutes).values({
      id: 'route-1',
      gameId: 'game-1',
      realm1Id: 'realm-a',
      realm2Id: 'realm-b',
      settlement1Id: 'settlement-a',
      settlement2Id: 'settlement-b',
      isActive: true,
      pathMode: 'land',
      productsExported1to2: '[]',
      productsExported2to1: '[]',
      protectedProducts: '[]',
      importSelectionState: '[]',
    }).run();

    db.insert(schema.turnReports).values({
      id: 'report-a',
      gameId: 'game-1',
      realmId: 'realm-a',
      year: 2,
      season: 'Spring',
      status: 'submitted',
    }).run();

    db.insert(schema.turnActions).values([
      {
        id: 'action-tax',
        turnReportId: 'report-a',
        gameId: 'game-1',
        realmId: 'realm-a',
        year: 2,
        season: 'Spring',
        kind: 'financial',
        status: 'submitted',
        outcome: 'pending',
        sortOrder: 0,
        description: '',
        actionWords: '[]',
        financialType: 'taxChange',
        taxType: 'Levy',
        cost: 0,
        createdAt: new Date('2025-01-01T00:00:00Z'),
        updatedAt: new Date('2025-01-01T00:00:00Z'),
      },
      {
        id: 'action-build',
        turnReportId: 'report-a',
        gameId: 'game-1',
        realmId: 'realm-a',
        year: 2,
        season: 'Spring',
        kind: 'financial',
        status: 'submitted',
        outcome: 'pending',
        sortOrder: 1,
        description: 'Raise border fortifications',
        actionWords: '[]',
        financialType: 'build',
        buildingType: 'Fort',
        territoryId: 'territory-a',
        locationType: 'territory',
        cost: 1500,
        createdAt: new Date('2025-01-01T00:00:00Z'),
        updatedAt: new Date('2025-01-01T00:00:00Z'),
      },
      {
        id: 'action-recruit',
        turnReportId: 'report-a',
        gameId: 'game-1',
        realmId: 'realm-a',
        year: 2,
        season: 'Spring',
        kind: 'financial',
        status: 'submitted',
        outcome: 'pending',
        sortOrder: 2,
        description: 'Muster archers',
        actionWords: '[]',
        financialType: 'recruit',
        troopType: 'Archers',
        settlementId: 'settlement-a',
        cost: 250,
        createdAt: new Date('2025-01-01T00:00:00Z'),
        updatedAt: new Date('2025-01-01T00:00:00Z'),
      },
    ]).run();

    db.insert(schema.turnEvents).values({
      id: 'event-1',
      gameId: 'game-1',
      year: 2,
      season: 'Spring',
      realmId: 'realm-a',
      kind: 'gm_event',
      status: 'open',
      title: 'Harsh rationing',
      description: 'Harsh rationing',
      payload: '{}',
      mechanicalEffect: JSON.stringify([
        {
          treasuryDelta: 200,
          foodNeededDelta: 1,
        },
      ]),
      resolution: null,
      autoGenerated: false,
      resolvedAt: null,
      resolvedBy: null,
    }).run();

    const result = service.advanceGameTurn('game-1', {
      expectedYear: 2,
      expectedSeason: 'Spring',
      idempotencyKey: 'game-1:2:Spring',
    });

    expect(result).toEqual({
      resolvedYear: 2,
      resolvedSeason: 'Spring',
      year: 2,
      season: 'Summer',
      phase: 'Submission',
      realmsResolved: 2,
      idempotencyKey: 'game-1:2:Spring',
      replayed: false,
    });

    const game = db.select().from(schema.games).where(eq(schema.games.id, 'game-1')).get();
    expect(game).toMatchObject({
      currentYear: 2,
      currentSeason: 'Summer',
      turnPhase: 'Submission',
    });

    const realmA = db.select().from(schema.realms).where(eq(schema.realms.id, 'realm-a')).get();
    expect(realmA).toMatchObject({
      treasury: 11600,
      taxType: 'Levy',
      foodBalance: -2,
      consecutiveFoodShortageSeasons: 2,
      consecutiveFoodRecoverySeasons: 0,
    });
    expect(JSON.parse(realmA!.turmoilSources)).toEqual([
      expect.objectContaining({
        id: 'ts-seasonal',
        amount: 2,
        seasonsRemaining: 1,
      }),
      expect.objectContaining({
        id: 'food-shortage:realm-a',
        amount: 3,
      }),
    ]);

    const existingCompletedBuilding = db.select().from(schema.buildings)
      .where(eq(schema.buildings.id, 'building-a-1'))
      .get();
    expect(existingCompletedBuilding).toMatchObject({
      constructionTurnsRemaining: 0,
      isOperational: true,
    });

    const insertedFort = db.select().from(schema.buildings)
      .where(eq(schema.buildings.type, 'Fort'))
      .get();
    expect(insertedFort).toMatchObject({
      settlementId: null,
      territoryId: 'territory-a',
      locationType: 'territory',
      constructionTurnsRemaining: 2,
      isOperational: false,
    });

    const insertedArchers = db.select().from(schema.troops)
      .where(eq(schema.troops.type, 'Archers'))
      .get();
    expect(insertedArchers).toMatchObject({
      realmId: 'realm-a',
      recruitmentTurnsRemaining: 0,
      garrisonSettlementId: 'settlement-a',
    });

    const existingTroop = db.select().from(schema.troops)
      .where(eq(schema.troops.id, 'troop-a-1'))
      .get();
    expect(existingTroop).toMatchObject({
      recruitmentTurnsRemaining: 0,
    });

    const report = db.select().from(schema.turnReports).where(eq(schema.turnReports.id, 'report-a')).get();
    expect(report).toMatchObject({ status: 'resolved' });

    const snapshots = db.select().from(schema.economicSnapshots).all();
    expect(snapshots).toHaveLength(2);
    const realmASnapshot = snapshots.find((snapshot) => snapshot.realmId === 'realm-a');
    expect(realmASnapshot).toMatchObject({
      year: 2,
      season: 'Spring',
      openingTreasury: 10000,
      totalRevenue: 3350,
      totalCosts: 1750,
      closingTreasury: 11600,
      taxTypeApplied: 'Levy',
    });
    expect(parseJson(realmASnapshot!.summary, {} as Record<string, unknown>)).toMatchObject({
      foodSurplus: -2,
      closingTurmoil: 15,
      pendingBuildings: 1,
      pendingTroops: 1,
    });

    const ledgerEntries = db.select().from(schema.economicEntries).where(eq(schema.economicEntries.realmId, 'realm-a')).all();
    expect(ledgerEntries).toEqual(expect.arrayContaining([
      expect.objectContaining({
        category: 'tax-revenue',
        amount: 3150,
      }),
      expect.objectContaining({
        category: 'gm-event-modifier',
        amount: 200,
      }),
      expect.objectContaining({
        category: 'report-build',
        amount: 1500,
      }),
      expect.objectContaining({
        category: 'report-recruit',
        amount: 250,
      }),
    ]));

    const route = db.select().from(schema.tradeRoutes).where(eq(schema.tradeRoutes.id, 'route-1')).get();
    expect(JSON.parse(route!.productsExported1to2)).toEqual(['Timber']);
    expect(JSON.parse(route!.productsExported2to1)).toEqual(['Gold']);

    const resolutionRows = db.select().from(schema.turnResolutions).all();
    expect(resolutionRows).toHaveLength(1);

    const replay = service.advanceGameTurn('game-1', {
      expectedYear: 2,
      expectedSeason: 'Spring',
      idempotencyKey: 'game-1:2:Spring',
    });

    expect(replay).toEqual({
      ...result!,
      replayed: true,
    });
    expect(db.select().from(schema.turnResolutions).all()).toHaveLength(1);
    expect(db.select().from(schema.economicSnapshots).all()).toHaveLength(2);

    sqlite.close();
  });

  it('persists food-shortage recovery by clearing the stored turmoil source on the second recovery turn', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-recovery',
      name: 'Recovery Test',
      gmCode: 'gm-recovery',
      playerCode: 'player-recovery',
      currentYear: 5,
      currentSeason: 'Autumn',
      turnPhase: 'Submission',
    }).run();

    db.insert(schema.realms).values({
      id: 'realm-recovery',
      gameId: 'game-recovery',
      name: 'Granary',
      governmentType: 'Monarch',
      treasury: 4000,
      taxType: 'Tribute',
      consecutiveFoodShortageSeasons: 3,
      consecutiveFoodRecoverySeasons: 1,
      turmoilSources: JSON.stringify([
        {
          id: 'food-shortage:realm-recovery',
          kind: 'food_shortage',
          description: 'Food shortage unrest',
          amount: 2,
          durationType: 'permanent',
          originYear: 5,
          originSeason: 'Summer',
          linkedEntityType: 'event',
          linkedEntityId: 'realm-recovery',
          autoGenerated: true,
          notes: null,
        },
      ]),
    }).run();

    db.insert(schema.territories).values({
      id: 'territory-recovery',
      gameId: 'game-recovery',
      name: 'Granary Vale',
      realmId: 'realm-recovery',
    }).run();

    db.insert(schema.settlements).values({
      id: 'settlement-recovery',
      territoryId: 'territory-recovery',
      realmId: 'realm-recovery',
      name: 'Granary',
      size: 'Village',
    }).run();

    const result = service.advanceGameTurn('game-recovery', {
      expectedYear: 5,
      expectedSeason: 'Autumn',
      idempotencyKey: 'game-recovery:5:Autumn',
    });

    expect(result).toMatchObject({
      year: 5,
      season: 'Winter',
      replayed: false,
    });

    const realm = db.select().from(schema.realms).where(eq(schema.realms.id, 'realm-recovery')).get();
    expect(realm).toMatchObject({
      foodBalance: 3,
      consecutiveFoodShortageSeasons: 0,
      consecutiveFoodRecoverySeasons: 0,
    });
    expect(JSON.parse(realm!.turmoilSources)).toEqual([]);

    sqlite.close();
  });

  it('applies territory food caps during turn resolution', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-cap',
      name: 'Food Cap Test',
      gmCode: 'gm-cap',
      playerCode: 'player-cap',
      currentYear: 1,
      currentSeason: 'Summer',
      turnPhase: 'Submission',
    }).run();

    db.insert(schema.realms).values({
      id: 'realm-cap',
      gameId: 'game-cap',
      name: 'Lowfields',
      governmentType: 'Monarch',
      treasury: 1000,
      taxType: 'Tribute',
    }).run();

    db.insert(schema.territories).values({
      id: 'territory-cap',
      gameId: 'game-cap',
      name: 'Lowfields',
      realmId: 'realm-cap',
      foodCapBase: 3,
      foodCapBonus: 0,
    }).run();

    db.insert(schema.settlements).values([
      {
        id: 'settlement-cap-1',
        territoryId: 'territory-cap',
        realmId: 'realm-cap',
        name: 'Northfield',
        size: 'Village',
      },
      {
        id: 'settlement-cap-2',
        territoryId: 'territory-cap',
        realmId: 'realm-cap',
        name: 'Southfield',
        size: 'Village',
      },
    ]).run();

    service.advanceGameTurn('game-cap', {
      expectedYear: 1,
      expectedSeason: 'Summer',
      idempotencyKey: 'game-cap:1:Summer',
    });

    const realm = db.select().from(schema.realms).where(eq(schema.realms.id, 'realm-cap')).get();
    expect(realm).toMatchObject({
      treasury: 1900,
      foodBalance: 1,
    });

    const snapshot = db.select().from(schema.economicSnapshots).where(eq(schema.economicSnapshots.realmId, 'realm-cap')).get();
    expect(parseJson(snapshot!.summary, {} as Record<string, unknown>)).toMatchObject({
      foodProduced: 3,
      foodNeeded: 2,
      foodSurplus: 1,
    });

    sqlite.close();
  });

  it('rejects turn reports with multiple tax changes', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-tax',
      name: 'Tax Validation Test',
      gmCode: 'gm-tax',
      playerCode: 'player-tax',
      currentYear: 1,
      currentSeason: 'Spring',
      turnPhase: 'Submission',
    }).run();

    db.insert(schema.realms).values({
      id: 'realm-tax',
      gameId: 'game-tax',
      name: 'Ledgermarch',
      governmentType: 'Monarch',
      treasury: 1000,
      taxType: 'Tribute',
    }).run();

    db.insert(schema.territories).values({
      id: 'territory-tax',
      gameId: 'game-tax',
      name: 'Ledgermarch',
      realmId: 'realm-tax',
    }).run();

    db.insert(schema.settlements).values({
      id: 'settlement-tax',
      territoryId: 'territory-tax',
      realmId: 'realm-tax',
      name: 'Ledgermarch',
      size: 'Village',
    }).run();

    db.insert(schema.turnReports).values({
      id: 'report-tax',
      gameId: 'game-tax',
      realmId: 'realm-tax',
      year: 1,
      season: 'Spring',
      status: 'submitted',
    }).run();

    db.insert(schema.turnActions).values([
      {
        id: 'tax-action-1',
        turnReportId: 'report-tax',
        gameId: 'game-tax',
        realmId: 'realm-tax',
        year: 1,
        season: 'Spring',
        kind: 'financial',
        status: 'submitted',
        outcome: 'pending',
        sortOrder: 0,
        description: '',
        actionWords: '[]',
        financialType: 'taxChange',
        taxType: 'Tribute',
        cost: 0,
        createdAt: new Date('2025-01-01T00:00:00Z'),
        updatedAt: new Date('2025-01-01T00:00:00Z'),
      },
      {
        id: 'tax-action-2',
        turnReportId: 'report-tax',
        gameId: 'game-tax',
        realmId: 'realm-tax',
        year: 1,
        season: 'Spring',
        kind: 'financial',
        status: 'submitted',
        outcome: 'pending',
        sortOrder: 1,
        description: '',
        actionWords: '[]',
        financialType: 'taxChange',
        taxType: 'Levy',
        cost: 0,
        createdAt: new Date('2025-01-01T00:00:00Z'),
        updatedAt: new Date('2025-01-01T00:00:00Z'),
      },
    ]).run();

    try {
      service.advanceGameTurn('game-tax', {
        expectedYear: 1,
        expectedSeason: 'Spring',
      });
      throw new Error('Expected resolution to fail');
    } catch (error) {
      expect(error).toMatchObject({
        code: 'invalid_economy_inputs',
        status: 400,
        details: {
          errors: expect.arrayContaining([
            expect.objectContaining({
              realmId: 'realm-tax',
              message: 'Only one tax change can be submitted in a turn.',
            }),
          ]),
        },
      });
    }

    sqlite.close();
  });

  it('rejects untyped GM event effects instead of bypassing the engine', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-2',
      name: 'Economy Test',
      gmCode: 'gm-code-2',
      playerCode: 'player-code-2',
      currentYear: 1,
      currentSeason: 'Autumn',
    }).run();

    db.insert(schema.realms).values({
      id: 'realm-2',
      gameId: 'game-2',
      name: 'Legacy',
      governmentType: 'Monarch',
      treasury: 1000,
      taxType: 'Tribute',
    }).run();

    db.insert(schema.territories).values({
      id: 'territory-2',
      gameId: 'game-2',
      name: 'Legacy Lands',
      realmId: 'realm-2',
    }).run();

    db.insert(schema.settlements).values({
      id: 'settlement-2',
      territoryId: 'territory-2',
      realmId: 'realm-2',
      name: 'Legacy Hold',
      size: 'Village',
    }).run();

    db.insert(schema.turnEvents).values({
      id: 'event-legacy',
      gameId: 'game-2',
      year: 1,
      season: 'Autumn',
      kind: 'gm_event',
      status: 'open',
      title: 'Legacy free-form modifier',
      description: 'Legacy free-form modifier',
      payload: '{}',
      mechanicalEffect: 'add 500 gold somehow',
      resolution: null,
      autoGenerated: false,
      resolvedAt: null,
      resolvedBy: null,
    }).run();

    try {
      service.advanceGameTurn('game-2', {
        expectedYear: 1,
        expectedSeason: 'Autumn',
      });
      throw new Error('Expected resolution to fail');
    } catch (error) {
      expect(error).toMatchObject({
        code: 'invalid_economy_inputs',
        status: 400,
      });
    }

    sqlite.close();
  });

  it('grows a settlement during turn resolution when it reaches one occupied slot short of full', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-growth',
      name: 'Growth Test',
      gmCode: 'gm-growth',
      playerCode: 'player-growth',
      currentYear: 1,
      currentSeason: 'Spring',
      turnPhase: 'Submission',
    }).run();

    db.insert(schema.realms).values({
      id: 'realm-growth',
      gameId: 'game-growth',
      name: 'Stonefield',
      governmentType: 'Monarch',
      treasury: 8000,
      taxType: 'Tribute',
    }).run();

    db.insert(schema.territories).values({
      id: 'territory-growth',
      gameId: 'game-growth',
      name: 'Stonefield Vale',
      realmId: 'realm-growth',
    }).run();

    db.insert(schema.settlements).values({
      id: 'settlement-growth',
      territoryId: 'territory-growth',
      realmId: 'realm-growth',
      name: 'Stonefield',
      size: 'Village',
    }).run();

    db.insert(schema.guildsOrdersSocieties).values({
      id: 'guild-growth',
      realmId: 'realm-growth',
      name: 'Stonefield Guild',
      type: 'Guild',
      income: 0,
    }).run();

    db.insert(schema.buildings).values([
      {
        id: 'growth-building-1',
        settlementId: 'settlement-growth',
        locationType: 'settlement',
        type: 'Theatre',
        category: 'Civic',
        size: 'Medium',
        takesBuildingSlot: true,
        isOperational: true,
        maintenanceState: 'active',
        constructionTurnsRemaining: 0,
      },
      {
        id: 'growth-building-2',
        settlementId: 'settlement-growth',
        locationType: 'settlement',
        type: 'Port',
        category: 'Civic',
        size: 'Medium',
        takesBuildingSlot: true,
        isOperational: true,
        maintenanceState: 'active',
        constructionTurnsRemaining: 0,
      },
    ]).run();

    db.insert(schema.turnReports).values({
      id: 'report-growth',
      gameId: 'game-growth',
      realmId: 'realm-growth',
      year: 1,
      season: 'Spring',
      status: 'submitted',
    }).run();

    db.insert(schema.turnActions).values({
      id: 'growth-action-build',
      turnReportId: 'report-growth',
      gameId: 'game-growth',
      realmId: 'realm-growth',
      year: 1,
      season: 'Spring',
      kind: 'financial',
      status: 'submitted',
      outcome: 'pending',
      sortOrder: 0,
      description: 'Open a bank',
      actionWords: '[]',
      financialType: 'build',
      buildingType: 'Bank',
      settlementId: 'settlement-growth',
      isGuildOwned: true,
      guildId: 'guild-growth',
      cost: 1500,
      createdAt: new Date('2025-01-01T00:00:00Z'),
      updatedAt: new Date('2025-01-01T00:00:00Z'),
    }).run();

    service.advanceGameTurn('game-growth', {
      expectedYear: 1,
      expectedSeason: 'Spring',
      idempotencyKey: 'game-growth:1:Spring',
    });

    const settlement = db.select().from(schema.settlements)
      .where(eq(schema.settlements.id, 'settlement-growth'))
      .get();
    expect(settlement).toMatchObject({ size: 'Town' });

    sqlite.close();
  });

  it('does not count slotless buildings toward settlement growth', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-slotless-growth',
      name: 'Slotless Growth Test',
      gmCode: 'gm-slotless-growth',
      playerCode: 'player-slotless-growth',
      currentYear: 1,
      currentSeason: 'Spring',
      turnPhase: 'Submission',
    }).run();

    db.insert(schema.realms).values({
      id: 'realm-slotless-growth',
      gameId: 'game-slotless-growth',
      name: 'Beaconreach',
      governmentType: 'Monarch',
      treasury: 8000,
      taxType: 'Tribute',
    }).run();

    db.insert(schema.territories).values({
      id: 'territory-slotless-growth',
      gameId: 'game-slotless-growth',
      name: 'Beaconreach Vale',
      realmId: 'realm-slotless-growth',
    }).run();

    db.insert(schema.settlements).values({
      id: 'settlement-slotless-growth',
      territoryId: 'territory-slotless-growth',
      realmId: 'realm-slotless-growth',
      name: 'Beaconreach',
      size: 'Village',
    }).run();

    db.insert(schema.resourceSites).values({
      id: 'resource-slotless-growth',
      territoryId: 'territory-slotless-growth',
      settlementId: 'settlement-slotless-growth',
      resourceType: 'Timber',
      rarity: 'Common',
    }).run();

    db.insert(schema.buildings).values([
      {
        id: 'slotless-growth-building-1',
        settlementId: 'settlement-slotless-growth',
        locationType: 'settlement',
        type: 'Theatre',
        category: 'Civic',
        size: 'Medium',
        takesBuildingSlot: true,
        isOperational: true,
        maintenanceState: 'active',
        constructionTurnsRemaining: 0,
      },
      {
        id: 'slotless-growth-building-2',
        settlementId: 'settlement-slotless-growth',
        locationType: 'settlement',
        type: 'Port',
        category: 'Civic',
        size: 'Medium',
        takesBuildingSlot: true,
        isOperational: true,
        maintenanceState: 'active',
        constructionTurnsRemaining: 0,
      },
    ]).run();

    db.insert(schema.turnReports).values({
      id: 'report-slotless-growth',
      gameId: 'game-slotless-growth',
      realmId: 'realm-slotless-growth',
      year: 1,
      season: 'Spring',
      status: 'submitted',
    }).run();

    db.insert(schema.turnActions).values({
      id: 'slotless-growth-action-build',
      turnReportId: 'report-slotless-growth',
      gameId: 'game-slotless-growth',
      realmId: 'realm-slotless-growth',
      year: 1,
      season: 'Spring',
      kind: 'financial',
      status: 'submitted',
      outcome: 'pending',
      sortOrder: 0,
      description: 'Raise a watchtower',
      actionWords: '[]',
      financialType: 'build',
      buildingType: 'Watchtower',
      settlementId: 'settlement-slotless-growth',
      material: 'Timber',
      cost: 750,
      createdAt: new Date('2025-01-01T00:00:00Z'),
      updatedAt: new Date('2025-01-01T00:00:00Z'),
    }).run();

    service.advanceGameTurn('game-slotless-growth', {
      expectedYear: 1,
      expectedSeason: 'Spring',
      idempotencyKey: 'game-slotless-growth:1:Spring',
    });

    const settlement = db.select().from(schema.settlements)
      .where(eq(schema.settlements.id, 'settlement-slotless-growth'))
      .get();
    expect(settlement).toMatchObject({ size: 'Village' });

    sqlite.close();
  });

  it('decrements army movement and completes arrival on season advance', () => {
    const { sqlite, db } = createTestDatabase();
    const service = createEconomyService(db);

    db.insert(schema.games).values({
      id: 'game-move',
      name: 'Army Movement Test',
      gmCode: 'gm-move',
      playerCode: 'player-move',
      currentYear: 1,
      currentSeason: 'Spring',
      turnPhase: 'Submission',
    }).run();

    db.insert(schema.realms).values({
      id: 'realm-move',
      gameId: 'game-move',
      name: 'Roadwatch',
      governmentType: 'Monarch',
      treasury: 1000,
      taxType: 'Tribute',
    }).run();

    db.insert(schema.territories).values([
      {
        id: 'territory-start',
        gameId: 'game-move',
        name: 'Start',
        realmId: 'realm-move',
      },
      {
        id: 'territory-destination',
        gameId: 'game-move',
        name: 'Destination',
        realmId: 'realm-move',
      },
    ]).run();

    db.insert(schema.settlements).values({
      id: 'settlement-move',
      territoryId: 'territory-start',
      realmId: 'realm-move',
      name: 'Roadwatch',
      size: 'Village',
    }).run();

    db.insert(schema.armies).values({
      id: 'army-move',
      realmId: 'realm-move',
      name: 'Marchers',
      locationTerritoryId: 'territory-start',
      destinationTerritoryId: 'territory-destination',
      movementTurnsRemaining: 1,
    }).run();

    service.advanceGameTurn('game-move', {
      expectedYear: 1,
      expectedSeason: 'Spring',
      idempotencyKey: 'game-move:1:Spring',
    });

    const army = db.select().from(schema.armies)
      .where(eq(schema.armies.id, 'army-move'))
      .get();

    expect(army).toMatchObject({
      id: 'army-move',
      locationTerritoryId: 'territory-destination',
      locationHexId: null,
      destinationTerritoryId: null,
      destinationHexId: null,
      movementTurnsRemaining: 0,
    });

    sqlite.close();
  });
});

function parseJson<T>(value: string, fallback: T): T {
  try {
    return JSON.parse(value) as T;
  } catch {
    return fallback;
  }
}
