import { SEASONS } from '@/lib/game-logic/constants';
import type { Season, TurmoilSource } from '@/types/game';

export interface GOSUnrestState {
  id: string;
  realmId: string;
  gosId: string;
  kind: string;
  severity: number;
  notes: string | null;
  startedYear: number;
  startedSeason: Season;
  expiresYear: number | null;
  expiresSeason: Season | null;
  resolvedAt: Date | null;
}

function compareTurns(yearA: number, seasonA: Season, yearB: number, seasonB: Season) {
  if (yearA !== yearB) {
    return yearA - yearB;
  }

  return SEASONS.indexOf(seasonA) - SEASONS.indexOf(seasonB);
}

function countRemainingSeasons(currentYear: number, currentSeason: Season, expiresYear: number, expiresSeason: Season) {
  const currentIndex = currentYear * SEASONS.length + SEASONS.indexOf(currentSeason);
  const expiryIndex = expiresYear * SEASONS.length + SEASONS.indexOf(expiresSeason);
  return expiryIndex - currentIndex + 1;
}

export function isActiveGOSUnrest(
  unrest: GOSUnrestState,
  currentYear: number,
  currentSeason: Season,
) {
  if (unrest.resolvedAt) {
    return false;
  }

  if (
    unrest.expiresYear === null
    || unrest.expiresYear === undefined
    || unrest.expiresSeason === null
    || unrest.expiresSeason === undefined
  ) {
    return true;
  }

  return compareTurns(currentYear, currentSeason, unrest.expiresYear, unrest.expiresSeason) <= 0;
}

export function mapGOSUnrestToTurmoilSource(
  unrest: GOSUnrestState,
  currentYear: number,
  currentSeason: Season,
): TurmoilSource {
  const hasExpiry = unrest.expiresYear !== null && unrest.expiresSeason !== null;

  return {
    id: unrest.id,
    kind: 'gos_unrest',
    description: `GOS unrest: ${unrest.kind}`,
    amount: unrest.severity,
    durationType: hasExpiry ? 'seasonal' : 'permanent',
    seasonsRemaining: hasExpiry
      ? Math.max(
        1,
        countRemainingSeasons(currentYear, currentSeason, unrest.expiresYear!, unrest.expiresSeason!),
      )
      : undefined,
    originYear: unrest.startedYear,
    originSeason: unrest.startedSeason,
    linkedEntityType: 'gos',
    linkedEntityId: unrest.gosId,
    autoGenerated: true,
    notes: unrest.notes,
  };
}

export function getActiveGOSUnrestSources(
  unrestStates: GOSUnrestState[],
  currentYear: number,
  currentSeason: Season,
) {
  return unrestStates
    .filter((unrest) => isActiveGOSUnrest(unrest, currentYear, currentSeason))
    .map((unrest) => mapGOSUnrestToTurmoilSource(unrest, currentYear, currentSeason));
}
