import { SEASONS } from '@/lib/game-logic/constants';
import type { Season, TurmoilSource } from '@/types/game';

export interface NobleGrievanceState {
  id: string;
  realmId: string;
  nobleId: string;
  kind: string;
  severity: number;
  sourceSettlementId: string | null;
  sourceTitle: string | null;
  notes: string | null;
  startedYear: number;
  startedSeason: Season;
  expiresYear: number | null;
  expiresSeason: Season | null;
  resolvedAt: Date | null;
}

function compareTurns(yearA: number, seasonA: Season, yearB: number, seasonB: Season) {
  if (yearA !== yearB) {
    return yearA - yearB;
  }

  return SEASONS.indexOf(seasonA) - SEASONS.indexOf(seasonB);
}

function countRemainingSeasons(currentYear: number, currentSeason: Season, expiresYear: number, expiresSeason: Season) {
  const currentIndex = currentYear * SEASONS.length + SEASONS.indexOf(currentSeason);
  const expiryIndex = expiresYear * SEASONS.length + SEASONS.indexOf(expiresSeason);
  return expiryIndex - currentIndex + 1;
}

export function isActiveNobleGrievance(
  grievance: NobleGrievanceState,
  currentYear: number,
  currentSeason: Season,
) {
  if (grievance.resolvedAt) {
    return false;
  }

  if (
    grievance.expiresYear === null
    || grievance.expiresYear === undefined
    || grievance.expiresSeason === null
    || grievance.expiresSeason === undefined
  ) {
    return true;
  }

  return compareTurns(currentYear, currentSeason, grievance.expiresYear, grievance.expiresSeason) <= 0;
}

export function mapNobleGrievanceToTurmoilSource(
  grievance: NobleGrievanceState,
  currentYear: number,
  currentSeason: Season,
): TurmoilSource {
  const hasExpiry = grievance.expiresYear !== null && grievance.expiresSeason !== null;

  return {
    id: grievance.id,
    kind: 'noble_grievance',
    description: grievance.sourceTitle?.trim() || `Noble grievance: ${grievance.kind}`,
    amount: grievance.severity,
    durationType: hasExpiry ? 'seasonal' : 'permanent',
    seasonsRemaining: hasExpiry
      ? Math.max(
        1,
        countRemainingSeasons(currentYear, currentSeason, grievance.expiresYear!, grievance.expiresSeason!),
      )
      : undefined,
    originYear: grievance.startedYear,
    originSeason: grievance.startedSeason,
    linkedEntityType: 'noble',
    linkedEntityId: grievance.nobleId,
    autoGenerated: true,
    notes: grievance.notes,
  };
}

export function getActiveNobleGrievanceSources(
  grievances: NobleGrievanceState[],
  currentYear: number,
  currentSeason: Season,
) {
  return grievances
    .filter((grievance) => isActiveNobleGrievance(grievance, currentYear, currentSeason))
    .map((grievance) => mapNobleGrievanceToTurmoilSource(grievance, currentYear, currentSeason));
}
