import { and, desc, eq, inArray, or } from 'drizzle-orm';
import { v4 as uuid } from 'uuid';
import { db as defaultDb, type DB, type DatabaseExecutor } from '@/db';
import {
  actionComments,
  buildings,
  nobles,
  realms,
  settlements,
  ships,
  troops,
  turnActions,
  turnEventAudiences,
  turnEvents,
} from '@/db/schema';
import { parseJson } from '@/lib/json';
import type {
  ActionCommentRecord,
  ActionKind,
  ActionWord,
  BuildingLocationType,
  BuildingSize,
  BuildingType,
  FinancialAction,
  FortificationMaterial,
  PendingFinancialAction,
  RecruitFinancialAction,
  ResolutionAbility,
  ResolutionQueueItem,
  Season,
  ShipType,
  TaxType,
  TroopType,
  TurnActionOutcome,
  TurnActionRecord,
  TurnActionResolutionRoll,
  TurnEventKind,
  TurnEventRecord,
  TurnEventStatus,
} from '@/types/game';

type TurnEventRow = typeof turnEvents.$inferSelect;
type TurnActionRow = typeof turnActions.$inferSelect;
type ActionCommentRow = typeof actionComments.$inferSelect;

export class TurnEventError extends Error {
  status: number;
  code: string;

  constructor(message: string, status: number, code: string) {
    super(message);
    this.status = status;
    this.code = code;
  }
}

export interface CreateTurnEventInput {
  gameId: string;
  year: number;
  season: Season;
  kind: TurnEventKind;
  status?: TurnEventStatus;
  title?: string | null;
  description: string;
  audienceRealmIds: string[];
  actionId?: string | null;
  causedByRealmId?: string | null;
  outcome?: TurnActionOutcome | null;
  rolls?: TurnActionResolutionRoll[];
  abilityUsed?: ResolutionAbility | null;
  abilityModifier?: number | null;
  nobleId?: string | null;
  payload?: Record<string, unknown>;
  mechanicalEffect?: string | null;
  resolution?: string | null;
  autoGenerated?: boolean;
  resolvedBy?: string | null;
}

function toIsoString(value: Date | null | undefined) {
  return value ? value.toISOString() : null;
}

function normalizeResolutionRolls(value: unknown): TurnActionResolutionRoll[] {
  if (!Array.isArray(value)) return [];

  return value.flatMap((roll): TurnActionResolutionRoll[] => {
    if (typeof roll !== 'object' || roll === null) return [];
    const candidate = roll as Partial<TurnActionResolutionRoll>;
    const sides = Number.isInteger(candidate.sides) && candidate.sides! >= 2 ? candidate.sides! : 6;
    const target = Number.isInteger(candidate.target) && candidate.target! >= 1 ? candidate.target! : 5;
    const dice = Array.isArray(candidate.dice)
      ? candidate.dice.filter((die): die is number => Number.isInteger(die) && die >= 1 && die <= sides)
      : [];
    if (dice.length === 0) return [];
    return [{
      dice,
      sides,
      target,
      successes: Number.isInteger(candidate.successes) ? candidate.successes! : dice.filter((die) => die >= target).length,
      failures: Number.isInteger(candidate.failures) ? candidate.failures! : dice.filter((die) => sides === 6 ? die <= 2 : die === 1).length,
      rolledAt: typeof candidate.rolledAt === 'string' ? candidate.rolledAt : null,
    }];
  });
}

function serializeComment(comment: ActionCommentRow): ActionCommentRecord {
  return {
    id: comment.id,
    actionId: comment.actionId,
    authorRole: comment.authorRole,
    authorLabel: comment.authorLabel,
    body: comment.body,
    createdAt: toIsoString(comment.createdAt),
  };
}

function serializeAction(action: TurnActionRow, comments: ActionCommentRecord[] = []): TurnActionRecord {
  return {
    id: action.id,
    turnReportId: action.turnReportId,
    gameId: action.gameId,
    realmId: action.realmId,
    year: action.year,
    season: action.season as Season,
    kind: action.kind as ActionKind,
    status: action.status,
    outcome: action.outcome,
    sortOrder: action.sortOrder,
    description: action.description,
    actionWords: parseJson<ActionWord[]>(action.actionWords, []),
    targetRealmId: action.targetRealmId ?? null,
    assignedNobleId: action.assignedNobleId ?? null,
    triggerCondition: action.triggerCondition ?? null,
    financialType: (action.financialType as FinancialAction['type'] | null) ?? null,
    buildingType: (action.buildingType as BuildingType | null) ?? null,
    troopType: (action.troopType as TroopType | null) ?? null,
    shipType: (action.shipType as ShipType | null) ?? null,
    fleetId: action.fleetId ?? null,
    settlementId: action.settlementId ?? null,
    territoryId: action.territoryId ?? null,
    material: (action.material as FortificationMaterial | null) ?? null,
    wallSize: (action.wallSize as BuildingSize | null) ?? null,
    ownerGosId: action.ownerGosId ?? null,
    allottedGosId: action.allottedGosId ?? null,
    locationType: (action.locationType as BuildingLocationType | null) ?? null,
    buildingSize: (action.buildingSize as BuildingSize | null) ?? null,
    takesBuildingSlot: action.takesBuildingSlot ?? null,
    constructionTurns: action.constructionTurns ?? null,
    taxType: (action.taxType as TaxType | null) ?? null,
    technicalKnowledgeKey: action.technicalKnowledgeKey ?? null,
    cost: action.cost,
    resolutionSummary: action.resolutionSummary ?? null,
    resolutionRolls: normalizeResolutionRolls(parseJson<unknown[]>(action.resolutionRolls, [])),
    submittedAt: toIsoString(action.submittedAt),
    submittedBy: action.submittedBy ?? null,
    executedAt: toIsoString(action.executedAt),
    executedBy: action.executedBy ?? null,
    createdAt: toIsoString(action.createdAt),
    updatedAt: toIsoString(action.updatedAt),
    comments,
  };
}

function mapAudiences(audienceRows: Array<typeof turnEventAudiences.$inferSelect>) {
  const byEvent = new Map<string, string[]>();
  for (const row of audienceRows) {
    const existing = byEvent.get(row.eventId) ?? [];
    existing.push(row.realmId);
    byEvent.set(row.eventId, existing);
  }
  return byEvent;
}

function serializeEvent(row: TurnEventRow, audienceRealmIds: string[] = row.realmId ? [row.realmId] : []): TurnEventRecord {
  return {
    id: row.id,
    gameId: row.gameId,
    year: row.year,
    season: row.season as Season,
    realmId: row.realmId,
    audienceRealmIds,
    actionId: row.actionId ?? null,
    causedByRealmId: row.causedByRealmId ?? null,
    kind: row.kind,
    status: row.status,
    outcome: (row.outcome as TurnActionOutcome | null) ?? null,
    rolls: normalizeResolutionRolls(parseJson<unknown[]>(row.rolls, [])),
    abilityUsed: (row.abilityUsed as ResolutionAbility | null) ?? null,
    abilityModifier: row.abilityModifier ?? null,
    nobleId: row.nobleId ?? null,
    title: row.title,
    description: row.description,
    resolution: row.resolution,
    autoGenerated: row.autoGenerated,
    resolvedAt: toIsoString(row.resolvedAt),
    resolvedBy: row.resolvedBy,
  };
}

function insertAudienceRows(database: DatabaseExecutor, eventId: string, audienceRealmIds: string[]) {
  for (const realmId of Array.from(new Set(audienceRealmIds))) {
    const insert = database.insert(turnEventAudiences).values({ eventId, realmId });
    if ('onConflictDoNothing' in insert && typeof insert.onConflictDoNothing === 'function') {
      insert.onConflictDoNothing().run();
    } else if ('run' in insert && typeof insert.run === 'function') {
      insert.run();
    }
  }
}

function runInsert(insert: unknown) {
  if (insert && typeof insert === 'object' && 'run' in insert && typeof insert.run === 'function') {
    insert.run();
  }
}

export function createTurnEventService(database: DB = defaultDb) {
  function createEvent(input: CreateTurnEventInput) {
    return typeof database.transaction === 'function'
      ? database.transaction((tx) => createEventInTransaction(tx, input))
      : createEventInTransaction(database, input);
  }

  function createEventInTransaction(tx: DatabaseExecutor, input: CreateTurnEventInput) {
    const audienceRealmIds = Array.from(new Set(input.audienceRealmIds.filter(Boolean)));
    if (audienceRealmIds.length === 0) {
      throw new TurnEventError('Events require at least one audience realm.', 400, 'missing_audience');
    }

    const id = uuid();
    const now = new Date();
    const row = {
      id,
      gameId: input.gameId,
      year: input.year,
      season: input.season,
      actionId: input.actionId ?? null,
      causedByRealmId: input.causedByRealmId ?? null,
      realmId: audienceRealmIds.length === 1 ? audienceRealmIds[0] : null,
      kind: input.kind,
      status: input.status ?? 'resolved',
      outcome: input.outcome ?? null,
      rolls: JSON.stringify(input.rolls ?? []),
      abilityUsed: input.abilityUsed ?? null,
      abilityModifier: input.abilityModifier ?? null,
      nobleId: input.nobleId ?? null,
      title: input.title ?? null,
      description: input.description,
      payload: JSON.stringify(input.payload ?? {}),
      mechanicalEffect: input.mechanicalEffect ?? null,
      resolution: input.resolution ?? null,
      autoGenerated: input.autoGenerated ?? false,
      resolvedAt: (input.status ?? 'resolved') === 'resolved' ? now : null,
      resolvedBy: input.resolvedBy ?? null,
    } satisfies typeof turnEvents.$inferInsert;

    runInsert(tx.insert(turnEvents).values(row));
    insertAudienceRows(tx, id, audienceRealmIds);
    return serializeEvent(row as TurnEventRow, audienceRealmIds);
  }

  function getEventsForRealm(gameId: string, realmId: string, year?: number, season?: Season) {
    const audienceRows = database
      .select()
      .from(turnEventAudiences)
      .where(eq(turnEventAudiences.realmId, realmId))
      .all();
    if (audienceRows.length === 0) return [];

    const eventIds = audienceRows.map((row) => row.eventId);
    const conditions = [eq(turnEvents.gameId, gameId), inArray(turnEvents.id, eventIds)];
    if (year !== undefined) conditions.push(eq(turnEvents.year, year));
    if (season !== undefined) conditions.push(eq(turnEvents.season, season));

    const rows = database.select().from(turnEvents).where(and(...conditions)).orderBy(desc(turnEvents.year)).all();
    const audiencesByEvent = mapAudiences(database.select().from(turnEventAudiences).where(inArray(turnEventAudiences.eventId, eventIds)).all());
    return rows.map((row) => serializeEvent(row, audiencesByEvent.get(row.id) ?? []));
  }

  function getOpenResolutionsForGame(gameId: string, year: number, season: Season): ResolutionQueueItem[] {
    const openEvents = database.select().from(turnEvents).where(and(
      eq(turnEvents.gameId, gameId),
      eq(turnEvents.year, year),
      eq(turnEvents.season, season),
      eq(turnEvents.status, 'open'),
    )).all();
    const actionRows = database.select().from(turnActions).where(and(
      eq(turnActions.gameId, gameId),
      or(eq(turnActions.status, 'submitted'), eq(turnActions.status, 'pending')),
    )).all();

    const realmIds = Array.from(new Set([
      ...openEvents.flatMap((event) => [event.realmId, event.causedByRealmId].filter(Boolean) as string[]),
      ...actionRows.map((action) => action.realmId),
    ]));
    const realmRows = realmIds.length > 0 ? database.select().from(realms).where(inArray(realms.id, realmIds)).all() : [];
    const realmById = new Map(realmRows.map((realm) => [realm.id, realm]));
    const nobleIds = Array.from(new Set(actionRows.map((action) => action.assignedNobleId).filter(Boolean) as string[]));
    const nobleRows = nobleIds.length > 0 ? database.select().from(nobles).where(inArray(nobles.id, nobleIds)).all() : [];
    const nobleById = new Map(nobleRows.map((noble) => [noble.id, noble]));
    const eventIds = openEvents.map((event) => event.id);
    const audiencesByEvent = eventIds.length > 0
      ? mapAudiences(database.select().from(turnEventAudiences).where(inArray(turnEventAudiences.eventId, eventIds)).all())
      : new Map<string, string[]>();

    return [
      ...openEvents.map((event) => ({
        id: event.id,
        type: 'event' as const,
        action: null,
        event: serializeEvent(event, audiencesByEvent.get(event.id) ?? []),
        realmId: event.causedByRealmId ?? event.realmId,
        realmName: event.causedByRealmId || event.realmId ? realmById.get(event.causedByRealmId ?? event.realmId!)?.name ?? null : null,
        assignedNoble: null,
        audienceRealmIds: audiencesByEvent.get(event.id) ?? [],
      })),
      ...actionRows.map((action) => {
        const noble = action.assignedNobleId ? nobleById.get(action.assignedNobleId) : null;
        const audienceRealmIds = [action.realmId, action.targetRealmId].filter(Boolean) as string[];
        return {
          id: action.id,
          type: 'action' as const,
          action: serializeAction(action),
          event: null,
          realmId: action.realmId,
          realmName: realmById.get(action.realmId)?.name ?? null,
          assignedNoble: noble ? {
            id: noble.id,
            name: noble.name,
            reasonSkill: noble.reasonSkill,
            cunningSkill: noble.cunningSkill,
          } : null,
          audienceRealmIds,
        };
      }),
    ];
  }

  function getPendingFinancialActionsForRealm(realmId: string): PendingFinancialAction[] {
    const actions = database.select().from(turnActions).where(and(
      eq(turnActions.realmId, realmId),
      eq(turnActions.kind, 'financial'),
      eq(turnActions.status, 'pending'),
    )).all();
    if (actions.length === 0) return [];
    const actionIds = actions.map((action) => action.id);
    const comments = database.select().from(actionComments).where(inArray(actionComments.actionId, actionIds)).all();
    const commentsByAction = new Map<string, ActionCommentRecord[]>();
    for (const comment of comments) {
      const existing = commentsByAction.get(comment.actionId) ?? [];
      existing.push(serializeComment(comment));
      commentsByAction.set(comment.actionId, existing);
    }

    const buildingRows = database.select().from(buildings).where(inArray(buildings.originatingActionId, actionIds)).all();
    const troopRows = database.select().from(troops).where(inArray(troops.originatingActionId, actionIds)).all();
    const shipRows = database.select().from(ships).where(inArray(ships.originatingActionId, actionIds)).all();
    const settlementIds = Array.from(new Set([
      ...buildingRows.map((row) => row.settlementId).filter(Boolean),
      ...troopRows.map((row) => row.garrisonSettlementId).filter(Boolean),
      ...shipRows.map((row) => row.constructionSettlementId ?? row.garrisonSettlementId).filter(Boolean),
    ] as string[]));
    const settlementRows = settlementIds.length > 0 ? database.select().from(settlements).where(inArray(settlements.id, settlementIds)).all() : [];
    const settlementById = new Map(settlementRows.map((settlement) => [settlement.id, settlement.name]));
    const actionById = new Map(actions.map((action) => [action.id, action]));

    return [
      ...buildingRows.map((row) => {
        const action = actionById.get(row.originatingActionId!)!;
        return {
          action: serializeAction(action, commentsByAction.get(action.id) ?? []),
          entityId: row.id,
          entityType: 'building' as const,
          entityLabel: row.type,
          targetLabel: row.settlementId ? settlementById.get(row.settlementId) ?? null : null,
          turnsRemaining: row.constructionTurnsRemaining,
          originatingTurn: { year: action.year, season: action.season as Season, submittedAt: toIsoString(action.submittedAt) },
        };
      }),
      ...troopRows.map((row) => {
        const action = actionById.get(row.originatingActionId!)!;
        return {
          action: serializeAction(action, commentsByAction.get(action.id) ?? []),
          entityId: row.id,
          entityType: 'troop' as const,
          entityLabel: row.type as RecruitFinancialAction['troopType'],
          targetLabel: row.garrisonSettlementId ? settlementById.get(row.garrisonSettlementId) ?? null : null,
          turnsRemaining: row.recruitmentTurnsRemaining,
          originatingTurn: { year: action.year, season: action.season as Season, submittedAt: toIsoString(action.submittedAt) },
        };
      }),
      ...shipRows.map((row) => {
        const action = actionById.get(row.originatingActionId!)!;
        const settlementId = row.constructionSettlementId ?? row.garrisonSettlementId;
        return {
          action: serializeAction(action, commentsByAction.get(action.id) ?? []),
          entityId: row.id,
          entityType: 'ship' as const,
          entityLabel: row.type,
          targetLabel: settlementId ? settlementById.get(settlementId) ?? null : null,
          turnsRemaining: row.constructionTurnsRemaining,
          originatingTurn: { year: action.year, season: action.season as Season, submittedAt: toIsoString(action.submittedAt) },
        };
      }),
    ].sort((left, right) => right.turnsRemaining - left.turnsRemaining);
  }

  return {
    createEvent,
    createEventInTransaction,
    getEventsForRealm,
    getOpenResolutionsForGame,
    getPendingFinancialActionsForRealm,
  };
}

const turnEventService = createTurnEventService();

export const createEvent = turnEventService.createEvent;
export const getEventsForRealm = turnEventService.getEventsForRealm;
export const getOpenResolutionsForGame = turnEventService.getOpenResolutionsForGame;
export const getPendingFinancialActionsForRealm = turnEventService.getPendingFinancialActionsForRealm;
