import { NextResponse } from 'next/server';
import { db } from '@/db';
import { games, realms, settlements, territories, troops, siegeUnits } from '@/db/schema';
import { eq } from 'drizzle-orm';
import { v4 as uuid } from 'uuid';
import { isAuthError, requireGM } from '@/lib/auth';
import type { TurmoilSource, Season } from '@/types/game';

export async function POST(
  request: Request,
  { params }: { params: Promise<{ gameId: string; settlementId: string }> },
) {
  try {
    const { gameId, settlementId } = await params;
    await requireGM(gameId);

    const body = await request.json();
    const { targetRealmId, transferTerritory = false } = body as {
      targetRealmId: string;
      transferTerritory?: boolean;
    };

    if (!targetRealmId) {
      return NextResponse.json({ error: 'targetRealmId is required' }, { status: 400 });
    }

    // Load settlement, target realm, and game
    const settlement = await db.select().from(settlements).where(eq(settlements.id, settlementId)).get();
    if (!settlement) {
      return NextResponse.json({ error: 'Settlement not found' }, { status: 404 });
    }

    const targetRealm = await db.select().from(realms).where(eq(realms.id, targetRealmId)).get();
    if (!targetRealm) {
      return NextResponse.json({ error: 'Target realm not found' }, { status: 404 });
    }

    const game = await db.select().from(games).where(eq(games.id, gameId)).get();
    if (!game) {
      return NextResponse.json({ error: 'Game not found' }, { status: 404 });
    }

    const previousRealmId = settlement.realmId;
    if (previousRealmId === targetRealmId) {
      return NextResponse.json({ error: 'Settlement already belongs to this realm' }, { status: 400 });
    }

    const currentSeason = game.currentSeason as Season;
    const currentYear = game.currentYear;

    // Transfer the settlement
    await db.update(settlements)
      .set({ realmId: targetRealmId, governingNobleId: null })
      .where(eq(settlements.id, settlementId));

    // Transfer garrison troops and siege units to new realm
    await db.update(troops)
      .set({ realmId: targetRealmId })
      .where(eq(troops.garrisonSettlementId, settlementId));
    await db.update(siegeUnits)
      .set({ realmId: targetRealmId })
      .where(eq(siegeUnits.garrisonSettlementId, settlementId));

    // Optionally transfer the parent territory
    if (transferTerritory) {
      await db.update(territories)
        .set({ realmId: targetRealmId })
        .where(eq(territories.id, settlement.territoryId));
    }

    // Add turmoil sources to both realms
    const turmoilAmount = 1;

    if (previousRealmId) {
      const losingRealm = await db.select().from(realms).where(eq(realms.id, previousRealmId)).get();
      if (losingRealm) {
        const existingSources: TurmoilSource[] = JSON.parse(losingRealm.turmoilSources || '[]');
        const newSource: TurmoilSource = {
          id: uuid(),
          kind: 'gm_event',
          description: `Lost ${settlement.name} to ${targetRealm.name}`,
          amount: turmoilAmount,
          durationType: 'seasonal',
          seasonsRemaining: 4,
          originYear: currentYear,
          originSeason: currentSeason,
          linkedEntityType: 'settlement',
          linkedEntityId: settlementId,
          autoGenerated: true,
        };
        await db.update(realms)
          .set({ turmoilSources: JSON.stringify([...existingSources, newSource]) })
          .where(eq(realms.id, previousRealmId));
      }
    }

    // Gaining realm gets a smaller turmoil bump (occupied populace unrest)
    const gainingRealm = await db.select().from(realms).where(eq(realms.id, targetRealmId)).get();
    if (gainingRealm) {
      const existingSources: TurmoilSource[] = JSON.parse(gainingRealm.turmoilSources || '[]');
      const newSource: TurmoilSource = {
        id: uuid(),
        kind: 'gm_event',
        description: `Captured ${settlement.name} — occupied populace unrest`,
        amount: turmoilAmount,
        durationType: 'seasonal',
        seasonsRemaining: 2,
        originYear: currentYear,
        originSeason: currentSeason,
        linkedEntityType: 'settlement',
        linkedEntityId: settlementId,
        autoGenerated: true,
      };
      await db.update(realms)
        .set({ turmoilSources: JSON.stringify([...existingSources, newSource]) })
        .where(eq(realms.id, targetRealmId));
    }

    return NextResponse.json({
      transferred: true,
      settlementId,
      previousRealmId,
      newRealmId: targetRealmId,
      territoryTransferred: transferTerritory,
    });
  } catch (error) {
    if (isAuthError(error)) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    throw error;
  }
}
