'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { TechnicalKnowledgeBadges } from '@/components/technical-knowledge/technical-knowledge-badges';
import { TerritoryHexMap } from '@/components/map/TerritoryHexMap';
import { NobleAssignmentSelect } from '@/components/governance/NobleAssignmentSelect';
import { NobleStatusEditor } from '@/components/governance/NobleStatusEditor';
import { NobleActivityBadge } from '@/components/governance/NobleActivityBadge';
import { GmTurnReviewPanel } from '@/components/turn-actions/gm-turn-review-panel';
import { useRole } from '@/hooks/use-role';
import type { EconomyOverviewRealmDto } from '@/lib/economy-dto';
import type { GameMapData } from '@/components/map/types';
import { buildGameTerritoryMapData } from '@/lib/maps/territory-map';
import { TRADITION_DEFS } from '@/lib/game-logic/constants';
import { TECHNICAL_KNOWLEDGE_OPTIONS, parseTechnicalKnowledge } from '@/lib/technical-knowledge';
import type { GovernmentType, TechnicalKnowledgeKey, Tradition } from '@/types/game';

const GOVERNMENT_OPTIONS = [
  { value: 'Monarch', label: 'Monarch' },
  { value: 'ElectedMonarch', label: 'Elected Monarch' },
  { value: 'Council', label: 'Council' },
  { value: 'Ecclesiastical', label: 'Ecclesiastical' },
  { value: 'Consortium', label: 'Consortium' },
  { value: 'Magistrate', label: 'Magistrate' },
  { value: 'Warlord', label: 'Warlord' },
];

const TRADITION_OPTIONS = Object.entries(TRADITION_DEFS).map(([key, def]) => ({
  value: key,
  label: `${def.displayName} (${def.category})`,
}));

interface Game {
  id: string;
  name: string;
  currentYear: number;
  currentSeason: string;
  turnPhase: string;
  gamePhase: string;
  initState: string;
  gmSetupState: string;
  gmCode?: string;
  playerCode?: string;
}

interface TurmoilSourceDto {
  id: string;
  kind: string;
  description: string;
  amount: number;
  durationType: 'permanent' | 'seasonal';
  seasonsRemaining?: number;
  autoGenerated: boolean;
}

interface Realm {
  id: string;
  name: string;
  governmentType: string;
  treasury: number;
  isNPC: boolean;
  traditions: string;
  technicalKnowledge: TechnicalKnowledgeKey[];
  projectedTurmoil?: number | null;
  turmoilBreakdown?: TurmoilSourceDto[];
  openTurmoilEventId?: string | null;
  winterUnrestPending?: boolean;
}

interface RealmResponse extends Omit<Realm, 'technicalKnowledge'> {
  technicalKnowledge: string;
}

interface Territory {
  id: string;
  name: string;
  realmId: string | null;
  description: string | null;
  foodCapBase: number;
  foodCapBonus: number;
  hasRiverAccess: boolean;
  hasSeaAccess: boolean;
}

interface Settlement {
  id: string;
  name: string;
  size: string;
  territoryId: string;
  realmId: string | null;
  buildings: Building[];
}

interface Building {
  id: string;
  type: string;
  category: string;
  size: string;
  material: string | null;
  isOperational: boolean;
  constructionTurnsRemaining: number;
  settlementId: string | null;
  territoryId: string | null;
}

interface Troop {
  id: string;
  realmId: string;
  type: string;
  class: string;
  armourType: string;
  condition: number;
  armyId: string | null;
  garrisonSettlementId: string | null;
}

const SETTLEMENT_SIZE_OPTIONS = [
  { value: 'Village', label: 'Village' },
  { value: 'Town', label: 'Town' },
  { value: 'City', label: 'City' },
];

interface PlayerSlot {
  id: string;
  claimCode: string;
  territoryId: string;
  territoryName: string | null;
  realmId: string | null;
  displayName: string | null;
  status: 'claimed' | 'unclaimed';
  setupState: string;
  checklist: {
    realmCreated: boolean;
    rulerCreated: boolean;
    nobleSetupCompleted: boolean;
    guildOrderSocietySetupCompleted: boolean;
    startingArmyPresent: boolean;
    settlementsPlacedNamed: boolean;
    economyInitialized: boolean;
  } | null;
  missingRequirements: string[];
}

function formatSetupStateLabel(setupState: string) {
  return setupState
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function getSetupStateBadgeVariant(setupState: string): 'default' | 'gold' | 'green' {
  if (setupState === 'ready') {
    return 'green';
  }

  if (setupState === 'claimed' || setupState === 'realm_created' || setupState === 'ruler_created') {
    return 'gold';
  }

  return 'default';
}

async function getErrorMessage(response: Response, fallback: string) {
  try {
    const data = await response.json();

    if (Array.isArray(data?.blockers) && data.blockers.length > 0) {
      const blockerSummary = data.blockers
        .map((blocker: { displayName?: string | null; id: string; missingRequirements?: string[] }) => {
          const label = blocker.displayName?.trim() || blocker.id;
          const missing = Array.isArray(blocker.missingRequirements) ? blocker.missingRequirements.join(', ') : '';
          return missing ? `${label}: ${missing}` : label;
        })
        .join(' · ');

      if (typeof data?.error === 'string' && blockerSummary) {
        return `${data.error} — ${blockerSummary}`;
      }
    }

    if (typeof data?.error === 'string' && data.error.trim().length > 0) {
      return data.error;
    }
  } catch {}

  return fallback;
}

export default function GMDashboard() {
  const params = useParams();
  const router = useRouter();
  const gameId = params.gameId as string;
  const { role, loading: roleLoading } = useRole();
  const [game, setGame] = useState<Game | null>(null);
  const [realms, setRealms] = useState<Realm[]>([]);
  const [territories, setTerritories] = useState<Territory[]>([]);
  const [playerSlots, setPlayerSlots] = useState<PlayerSlot[]>([]);
  const [economyOverview, setEconomyOverview] = useState<Record<string, EconomyOverviewRealmDto>>({});
  const [loadingDashboard, setLoadingDashboard] = useState(true);
  const [starting, setStarting] = useState(false);
  const [markingReady, setMarkingReady] = useState(false);
  const [realmForm, setRealmForm] = useState({
    name: '',
    governmentType: 'Monarch' as GovernmentType,
    traditions: [] as Tradition[],
    technicalKnowledge: [] as TechnicalKnowledgeKey[],
    treasury: 0,
  });
  const [editingRealmId, setEditingRealmId] = useState<string | null>(null);
  const [savingRealm, setSavingRealm] = useState(false);
  const [showRealmForm, setShowRealmForm] = useState(false);
  const [error, setError] = useState('');
  const [worldSettlements, setWorldSettlements] = useState<Settlement[]>([]);
  const [expandedTerritory, setExpandedTerritory] = useState<string | null>(null);
  const [editingTerritoryId, setEditingTerritoryId] = useState<string | null>(null);
  const [editingSettlementId, setEditingSettlementId] = useState<string | null>(null);
  const [transferringSettlementId, setTransferringSettlementId] = useState<string | null>(null);
  const [transferTargetRealmId, setTransferTargetRealmId] = useState('');
  const [transferTerritory, setTransferTerritory] = useState(false);
  const [gameMapData, setGameMapData] = useState<GameMapData | null>(null);
  const [addingSettlement, setAddingSettlement] = useState<{ territoryId: string; name: string; size: string; hexId: string | null } | null>(null);
  const [turmoilForm, setTurmoilForm] = useState<{ realmId: string; description: string; amount: number; durationType: 'permanent' | 'seasonal'; seasonsRemaining: number; notes: string } | null>(null);
  const [savingTurmoil, setSavingTurmoil] = useState(false);

  const loadDashboard = useCallback(async () => {
    try {
      setLoadingDashboard(true);
      setError('');

      const [gameResponse, realmsResponse, territoriesResponse, slotsResponse, overviewResponse, settlementsResponse, mapResponse] = await Promise.all([
        fetch(`/api/game/${gameId}`, { cache: 'no-store' }),
        fetch(`/api/game/${gameId}/realms`, { cache: 'no-store' }),
        fetch(`/api/game/${gameId}/territories`, { cache: 'no-store' }),
        fetch(`/api/game/${gameId}/player-slots`, { cache: 'no-store' }),
        fetch(`/api/game/${gameId}/economy/overview`, { cache: 'no-store' }),
        fetch(`/api/game/${gameId}/settlements`, { cache: 'no-store' }),
        fetch(`/api/game/${gameId}/map`, { cache: 'no-store' }),
      ]);

      if (!gameResponse.ok) {
        throw new Error(await getErrorMessage(gameResponse, 'Failed to load the GM dashboard'));
      }

      if (!realmsResponse.ok || !territoriesResponse.ok || !slotsResponse.ok) {
        const failingResponse = [realmsResponse, territoriesResponse, slotsResponse].find((response) => !response.ok);
        throw new Error(await getErrorMessage(failingResponse!, 'Failed to load GM-only setup data'));
      }

      setGame(await gameResponse.json());
      const realmList: Realm[] = (await realmsResponse.json() as RealmResponse[]).map((realm) => ({
        ...realm,
        technicalKnowledge: parseTechnicalKnowledge(realm.technicalKnowledge),
      }));
      setRealms(realmList);
      setTerritories(await territoriesResponse.json());
      setPlayerSlots(await slotsResponse.json());
      if (settlementsResponse.ok) {
        setWorldSettlements(await settlementsResponse.json());
      }
      if (mapResponse.ok) {
        setGameMapData(await mapResponse.json());
      }
      if (overviewResponse.ok) {
        const overviewData = await overviewResponse.json();
        setEconomyOverview(Object.fromEntries(
          overviewData.realms.map((entry: EconomyOverviewRealmDto) => [entry.realmId, entry]),
        ));
      } else {
        setEconomyOverview({});
      }
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : 'Failed to load the GM dashboard');
    } finally {
      setLoadingDashboard(false);
    }
  }, [gameId]);

  useEffect(() => {
    if (roleLoading) {
      return;
    }

    if (role !== 'gm') {
      router.replace(`/game/${gameId}`);
      return;
    }

    void loadDashboard();
  }, [gameId, loadDashboard, role, roleLoading, router]);

  useEffect(() => {
    if (role !== 'gm') {
      return;
    }

    const intervalId = window.setInterval(() => {
      void loadDashboard();
    }, 5000);

    return () => window.clearInterval(intervalId);
  }, [loadDashboard, role]);

  async function startGame() {
    setStarting(true);
    setError('');

    try {
      const response = await fetch(`/api/game/${gameId}/start`, { method: 'POST' });

      if (!response.ok) {
        setError(await getErrorMessage(response, 'Failed to start the game'));
        return;
      }

      await loadDashboard();
    } finally {
      setStarting(false);
    }
  }

  async function markGMReady() {
    setMarkingReady(true);
    setError('');

    try {
      const response = await fetch(`/api/game/${gameId}/setup/gm-ready`, { method: 'POST' });

      if (!response.ok) {
        setError(await getErrorMessage(response, 'Failed to mark GM setup as ready'));
        return;
      }

      await loadDashboard();
    } finally {
      setMarkingReady(false);
    }
  }

  function openRealmForm(realm?: Realm) {
    if (realm) {
      setEditingRealmId(realm.id);
      setRealmForm({
        name: realm.name,
        governmentType: realm.governmentType as GovernmentType,
        traditions: JSON.parse(realm.traditions || '[]'),
        technicalKnowledge: realm.technicalKnowledge,
        treasury: realm.treasury,
      });
    } else {
      setEditingRealmId(null);
      setRealmForm({ name: '', governmentType: 'Monarch', traditions: [], technicalKnowledge: [], treasury: 0 });
    }
    setShowRealmForm(true);
  }

  function toggleTradition(tradition: Tradition) {
    setRealmForm((current) => {
      if (current.traditions.includes(tradition)) {
        return { ...current, traditions: current.traditions.filter((v) => v !== tradition) };
      }
      if (current.traditions.length >= 3) return current;
      return { ...current, traditions: [...current.traditions, tradition] };
    });
  }

  function toggleTechnicalKnowledge(knowledge: TechnicalKnowledgeKey) {
    setRealmForm((current) => ({
      ...current,
      technicalKnowledge: current.technicalKnowledge.includes(knowledge)
        ? current.technicalKnowledge.filter((entry) => entry !== knowledge)
        : [...current.technicalKnowledge, knowledge],
    }));
  }

  async function saveRealm() {
    setSavingRealm(true);
    setError('');

    try {
      const response = await fetch(`/api/game/${gameId}/realms`, {
        method: editingRealmId ? 'PATCH' : 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(editingRealmId
          ? {
            realmId: editingRealmId,
            name: realmForm.name,
            governmentType: realmForm.governmentType,
            traditions: realmForm.traditions,
            technicalKnowledge: realmForm.technicalKnowledge,
            treasury: realmForm.treasury,
          }
          : {
            name: realmForm.name,
            governmentType: realmForm.governmentType,
            traditions: realmForm.traditions,
            technicalKnowledge: realmForm.technicalKnowledge,
            treasury: realmForm.treasury,
            isNPC: true,
          }),
      });

      if (!response.ok) {
        setError(await getErrorMessage(response, 'Failed to save the realm'));
        return;
      }

      await loadDashboard();
      setShowRealmForm(false);
    } finally {
      setSavingRealm(false);
    }
  }

  async function addTurmoilSource() {
    if (!turmoilForm) return;
    setSavingTurmoil(true);
    setError('');
    try {
      const response = await fetch(`/api/game/${gameId}/realms/turmoil`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          realmId: turmoilForm.realmId,
          description: turmoilForm.description,
          amount: turmoilForm.amount,
          durationType: turmoilForm.durationType,
          seasonsRemaining: turmoilForm.durationType === 'seasonal' ? turmoilForm.seasonsRemaining : undefined,
          notes: turmoilForm.notes || null,
        }),
      });
      if (!response.ok) {
        setError(await getErrorMessage(response, 'Failed to add turmoil source'));
        return;
      }
      setTurmoilForm(null);
      await loadDashboard();
    } finally {
      setSavingTurmoil(false);
    }
  }

  async function removeTurmoilSource(realmId: string, sourceId: string) {
    setError('');
    const response = await fetch(`/api/game/${gameId}/realms/turmoil`, {
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ realmId, sourceId }),
    });
    if (!response.ok) {
      setError(await getErrorMessage(response, 'Failed to remove turmoil source'));
      return;
    }
    await loadDashboard();
  }

  async function assignTerritory(territoryId: string, realmId: string | null) {
    setError('');

    const response = await fetch(`/api/game/${gameId}/territories`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ territoryId, realmId }),
    });

    if (!response.ok) {
      setError(await getErrorMessage(response, 'Failed to update territory ownership'));
      return;
    }

    await loadDashboard();
  }

  function territoriesForRealm(realmId: string) {
    return territories.filter((t) => t.realmId === realmId);
  }

  const unassignedTerritories = territories.filter((t) => !t.realmId);

  async function saveTerritory(territoryId: string, updates: Partial<Territory>) {
    setError('');
    const response = await fetch(`/api/game/${gameId}/territories`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ territoryId, ...updates }),
    });
    if (!response.ok) {
      setError(await getErrorMessage(response, 'Failed to update territory'));
      return;
    }
    await loadDashboard();
  }

  async function saveSettlement(settlementId: string, updates: Record<string, unknown>) {
    setError('');
    const response = await fetch(`/api/game/${gameId}/settlements`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ settlementId, ...updates }),
    });
    if (!response.ok) {
      setError(await getErrorMessage(response, 'Failed to update settlement'));
      return;
    }
    await loadDashboard();
    setEditingSettlementId(null);
  }

  async function deleteSettlement(settlementId: string) {
    setError('');
    const response = await fetch(`/api/game/${gameId}/settlements`, {
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ settlementId }),
    });
    if (!response.ok) {
      setError(await getErrorMessage(response, 'Failed to delete settlement'));
      return;
    }
    await loadDashboard();
  }

  async function transferSettlement(settlementId: string) {
    if (!transferTargetRealmId) return;
    setError('');
    const response = await fetch(`/api/game/${gameId}/settlements/${settlementId}/transfer`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ targetRealmId: transferTargetRealmId, transferTerritory }),
    });
    if (!response.ok) {
      setError(await getErrorMessage(response, 'Failed to transfer settlement'));
      return;
    }
    setTransferringSettlementId(null);
    setTransferTargetRealmId('');
    setTransferTerritory(false);
    await loadDashboard();
  }

  async function addSettlement(territoryId: string, name: string, size: string, hexId: string | null) {
    setError('');
    const territory = territories.find((t) => t.id === territoryId);
    const response = await fetch(`/api/game/${gameId}/settlements`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ territoryId, name, size, realmId: territory?.realmId ?? null, hexId }),
    });
    if (!response.ok) {
      setError(await getErrorMessage(response, 'Failed to create settlement'));
      return;
    }
    setAddingSettlement(null);
    await loadDashboard();
  }

  async function deleteBuilding(buildingId: string) {
    setError('');
    const response = await fetch(`/api/game/${gameId}/buildings`, {
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ buildingId }),
    });
    if (!response.ok) {
      setError(await getErrorMessage(response, 'Failed to delete building'));
      return;
    }
    await loadDashboard();
  }

  const realmMap = Object.fromEntries(realms.map((r) => [r.id, r.name]));
  const addingTerritoryMap = useMemo(
    () => addingSettlement && gameMapData ? buildGameTerritoryMapData(gameMapData, addingSettlement.territoryId) : null,
    [addingSettlement, gameMapData]
  );

  if (roleLoading || role !== 'gm' || (loadingDashboard && !game)) {
    return (
      <main className="min-h-screen flex items-center justify-center">
        <p className="font-heading text-ink-300 text-lg">Loading GM dashboard...</p>
      </main>
    );
  }

  if (!game) {
    return null;
  }

  const isActive = game.initState === 'active' || game.initState === 'completed';
  const npcCount = realms.filter((realm) => realm.isNPC).length;
  const playerCount = realms.filter((realm) => !realm.isNPC).length;
  const allPlayersReady = playerSlots.length > 0 && playerSlots.every((slot) => slot.setupState === 'ready');
  const canStartGame = game.initState === 'ready_to_start' || (game.gmSetupState === 'ready' && allPlayersReady);
  const claimedPlayerSlots = playerSlots.filter((slot) => slot.status === 'claimed');

  return (
    <main className="min-h-screen p-6 max-w-6xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold">{game.name}</h1>
          <p className="text-ink-300">GM Dashboard</p>
        </div>
        <div className="flex items-center gap-3">
          {game.initState !== 'active' && game.initState !== 'completed' && (
            <Badge>Init: {game.initState}</Badge>
          )}
          {game.initState !== 'active' && game.initState !== 'completed' && (
            <Badge variant={game.gmSetupState === 'ready' ? 'green' : 'gold'}>GM Setup: {game.gmSetupState}</Badge>
          )}
          <Badge variant="gold">Phase: {game.gamePhase}</Badge>
          <Badge>Year {game.currentYear}, {game.currentSeason}</Badge>
          <Badge>Turn: {game.turnPhase}</Badge>
        </div>
      </div>

      {error && <p className="mb-4 text-sm text-red-500">{error}</p>}

      {!isActive && (
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4 mb-6">
          <Card>
            <CardContent>
              <p className="text-sm text-ink-300 pt-4">GM Code</p>
              <p className="font-mono text-2xl">{game.gmCode || '—'}</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <p className="text-sm text-ink-300 pt-4">Player Slots</p>
              <p className="text-3xl font-heading font-bold">{playerSlots.length}</p>
              <p className="text-sm text-ink-300">{playerSlots.filter((slot) => slot.status === 'claimed').length} claimed</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent>
              <p className="text-sm text-ink-300 pt-4">Realms</p>
              <p className="text-3xl font-heading font-bold">{realms.length}</p>
              <p className="text-sm text-ink-300">{npcCount} NPC / {playerCount} player</p>
            </CardContent>
          </Card>
        </div>
      )}

      <div className="flex gap-3 mb-6">
        {!isActive && game.gmSetupState !== 'ready' && (
          <Button variant="outline" onClick={() => void markGMReady()} disabled={markingReady}>
            {markingReady ? 'Saving...' : 'Mark GM Setup Ready'}
          </Button>
        )}
        {canStartGame && !isActive && (
          <Button variant="accent" onClick={() => void startGame()} disabled={starting}>
            {starting ? 'Starting...' : 'Start Game'}
          </Button>
        )}
        <Button variant="ghost" onClick={() => void loadDashboard()} disabled={loadingDashboard}>
          {loadingDashboard ? 'Refreshing...' : 'Refresh'}
        </Button>
        <Link href={`/game/${gameId}/map`}>
          <Button variant="outline">Map</Button>
        </Link>
        <Button
          variant="outline"
          onClick={() => {
            const a = document.createElement('a');
            a.href = `/api/game/${gameId}/export`;
            a.download = '';
            a.click();
          }}
        >
          Export Database
        </Button>
      </div>

      {!isActive && (
        <>
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle>Player Slots</CardTitle>
                <Link href={`/game/${gameId}/gm/realm-slots`}>
                  <Button variant="outline" size="sm">Manage Realm Slots</Button>
                </Link>
              </div>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {playerSlots.map((slot) => (
                  <div key={slot.id} className="p-3 medieval-border rounded flex items-center justify-between gap-4">
                    <div>
                      <p className="font-heading font-semibold">{slot.territoryName || slot.territoryId}</p>
                      <p className="text-sm text-ink-300">{slot.displayName || 'Unlabeled player slot'}</p>
                    </div>
                    <div className="text-right">
                      <Badge variant={slot.status === 'claimed' ? 'green' : 'gold'}>{slot.status}</Badge>
                      <p className="text-xs text-ink-300 mt-1">{slot.setupState}</p>
                      <p className="font-mono text-lg mt-1">{slot.claimCode}</p>
                    </div>
                  </div>
                ))}
                {playerSlots.length === 0 && <p className="text-ink-300 text-sm">No player slots yet.</p>}
              </div>
            </CardContent>
          </Card>

          <Card className="mt-6">
            <CardHeader>
              <CardTitle>Claimed Player Progress</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {claimedPlayerSlots.map((slot) => {
                  const completedChecklistItems = slot.checklist
                    ? Object.values(slot.checklist).filter(Boolean).length
                    : 0;

                  return (
                    <div key={slot.id} className="rounded border border-card-border bg-parchment-100/40 p-4 space-y-3">
                      <div className="flex items-start justify-between gap-4">
                        <div>
                          <p className="font-heading font-semibold">{slot.displayName || slot.territoryName || 'Claimed slot'}</p>
                          <p className="text-sm text-ink-300">
                            {slot.territoryName || slot.territoryId}
                            {slot.realmId ? ` · realm created` : ' · realm not created yet'}
                          </p>
                        </div>
                        <div className="text-right">
                          <Badge variant={getSetupStateBadgeVariant(slot.setupState)}>
                            {formatSetupStateLabel(slot.setupState)}
                          </Badge>
                          <p className="mt-1 text-xs text-ink-300">
                            {slot.checklist ? `${completedChecklistItems}/7 setup items complete` : 'Awaiting setup data'}
                          </p>
                        </div>
                      </div>
                      {slot.missingRequirements.length > 0 ? (
                        <div className="flex flex-wrap gap-2">
                          {slot.missingRequirements.map((requirement) => (
                            <Badge key={`${slot.id}-${requirement}`} variant="default">
                              Missing: {requirement}
                            </Badge>
                          ))}
                        </div>
                      ) : (
                        <p className="text-sm text-green-700">All player setup requirements are complete.</p>
                      )}
                    </div>
                  );
                })}
                {claimedPlayerSlots.length === 0 && (
                  <p className="text-sm text-ink-300">No player slots have been claimed yet.</p>
                )}
              </div>
            </CardContent>
          </Card>
        </>
      )}

      {isActive && <GmTurnReviewPanel gameId={gameId} />}

      <Card className="mt-6">
        <CardHeader className="flex flex-row items-center justify-between">
          <CardTitle>{isActive ? 'Realms' : 'All Realms'}</CardTitle>
          {!showRealmForm && (
            <Button variant="outline" onClick={() => openRealmForm()}>
              + Add NPC Realm
            </Button>
          )}
        </CardHeader>
        <CardContent>
          {showRealmForm && (
            <div className="p-4 medieval-border rounded mb-4 space-y-3">
              <p className="font-heading font-semibold">{editingRealmId ? 'Edit Realm' : 'New NPC Realm'}</p>
              <Input
                label="Realm Name"
                value={realmForm.name}
                onChange={(e) => setRealmForm((c) => ({ ...c, name: e.target.value }))}
              />
              <Select
                label="Government"
                options={GOVERNMENT_OPTIONS}
                value={realmForm.governmentType}
                onChange={(e) => setRealmForm((c) => ({ ...c, governmentType: e.target.value as GovernmentType }))}
              />
              <div>
                <p className="font-heading text-sm font-medium text-ink-500 mb-2">Traditions ({realmForm.traditions.length}/3)</p>
                <div className="flex flex-wrap gap-2">
                  {TRADITION_OPTIONS.map((option) => (
                    <Badge
                      key={option.value}
                      variant={realmForm.traditions.includes(option.value as Tradition) ? 'gold' : 'default'}
                      className="cursor-pointer"
                      onClick={() => toggleTradition(option.value as Tradition)}
                    >
                      {option.label}
                    </Badge>
                  ))}
                </div>
              </div>
              <Input
                label="Treasury (gc)"
                type="number"
                value={String(realmForm.treasury)}
                onChange={(e) => setRealmForm((c) => ({ ...c, treasury: Number(e.target.value) || 0 }))}
              />
              <div>
                <div className="mb-2 flex items-center justify-between gap-3">
                  <p className="font-heading text-sm font-medium text-ink-500">
                    Technical Knowledge ({realmForm.technicalKnowledge.length})
                  </p>
                  <span className="text-xs text-ink-300">GM-managed</span>
                </div>
                <p className="mb-3 text-sm text-ink-300">
                  Select the local technical knowledge this realm can use without trade access.
                </p>
                <div className="mb-3">
                  <TechnicalKnowledgeBadges
                    knowledge={realmForm.technicalKnowledge}
                    emptyLabel="No technical knowledge assigned."
                    variant="gold"
                  />
                </div>
                <div className="flex flex-wrap gap-2">
                  {TECHNICAL_KNOWLEDGE_OPTIONS.map((option) => {
                    const isSelected = realmForm.technicalKnowledge.includes(option.value);

                    return (
                      <button
                        key={option.value}
                        type="button"
                        className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-heading font-semibold transition-colors ${
                          isSelected
                            ? 'border-gold-500 bg-gold-400 text-ink-700'
                            : 'border-ink-200 bg-parchment-50 text-ink-500 hover:bg-parchment-200'
                        }`}
                        title={option.description}
                        onClick={() => toggleTechnicalKnowledge(option.value)}
                      >
                        {option.label}
                      </button>
                    );
                  })}
                </div>
              </div>

              {editingRealmId && (
                <div>
                  <p className="font-heading text-sm font-medium text-ink-500 mb-2">Territories</p>
                  <div className="space-y-2">
                    {territoriesForRealm(editingRealmId).map((territory) => (
                      <div key={territory.id} className="flex items-center justify-between p-2 bg-parchment-100 rounded">
                        <span className="text-sm">{territory.name}</span>
                        <Button
                          variant="ghost"
                          onClick={() => void assignTerritory(territory.id, null)}
                        >
                          Remove
                        </Button>
                      </div>
                    ))}
                    {territoriesForRealm(editingRealmId).length === 0 && (
                      <p className="text-ink-300 text-sm">No territories assigned.</p>
                    )}
                  </div>
                  {unassignedTerritories.length > 0 && (
                    <div className="mt-2">
                      <Select
                        label="Add Territory"
                        placeholder="Select a territory..."
                        options={unassignedTerritories.map((t) => ({ value: t.id, label: t.name }))}
                        value=""
                        onChange={(e) => {
                          if (e.target.value) void assignTerritory(e.target.value, editingRealmId);
                        }}
                      />
                    </div>
                  )}
                </div>
              )}

              <div className="flex gap-2">
                <Button variant="accent" onClick={() => void saveRealm()} disabled={savingRealm || !realmForm.name.trim()}>
                  {savingRealm ? 'Saving...' : editingRealmId ? 'Update Realm' : 'Create Realm'}
                </Button>
                <Button variant="outline" onClick={() => setShowRealmForm(false)}>Cancel</Button>
              </div>
            </div>
          )}
          <div className="space-y-3">
            {realms.map((realm) => {
              const realmTerritories = territoriesForRealm(realm.id);
              const slotForRealm = playerSlots.find((s) => s.realmId === realm.id);
              return (
                <div key={realm.id} className="p-3 medieval-border rounded space-y-2">
                  <div className="flex items-center justify-between">
                    <div>
                      <span className="font-heading font-semibold">{realm.name}</span>
                      <span className="text-ink-300 ml-2">{realm.governmentType}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      {realm.isNPC && (
                        <Link href={`/game/${gameId}/realm?realmId=${realm.id}`}>
                          <Button variant="outline">Manage Realm</Button>
                        </Link>
                      )}
                      <Button variant="outline" onClick={() => openRealmForm(realm)}>
                        Edit
                      </Button>
                      <Badge variant={realm.isNPC ? 'gold' : 'default'}>{realm.isNPC ? 'NPC' : 'Player'}</Badge>
                    </div>
                  </div>
                  <div className="flex items-center gap-3 text-sm">
                    <span>Treasury {realm.treasury.toLocaleString()}gc</span>
                    {economyOverview[realm.id] && (
                      <span className="text-ink-300">
                        Projected {economyOverview[realm.id].projectedTreasury.toLocaleString()}gc
                      </span>
                    )}
                    <Badge
                      variant={
                        (realm.projectedTurmoil ?? economyOverview[realm.id]?.projectedTurmoil ?? 0) > 5
                          ? 'red'
                          : (realm.projectedTurmoil ?? economyOverview[realm.id]?.projectedTurmoil ?? 0) > 2
                            ? 'gold'
                            : 'green'
                      }
                    >
                      Turmoil {realm.projectedTurmoil ?? economyOverview[realm.id]?.projectedTurmoil ?? 0}
                    </Badge>
                    {realm.openTurmoilEventId ? (
                      <Badge variant={realm.winterUnrestPending ? 'red' : 'gold'}>
                        {realm.winterUnrestPending ? 'Winter unrest' : 'Review open'}
                      </Badge>
                    ) : null}
                    {economyOverview[realm.id]?.warningCount ? (
                      <Badge variant="gold">{economyOverview[realm.id].warningCount} warnings</Badge>
                    ) : null}
                    {!realm.isNPC && slotForRealm && game.initState !== 'active' && game.initState !== 'completed' && (
                      <Badge variant={getSetupStateBadgeVariant(slotForRealm.setupState)}>
                        {formatSetupStateLabel(slotForRealm.setupState)}
                      </Badge>
                    )}
                  </div>
                  {!realm.isNPC && slotForRealm && slotForRealm.missingRequirements.length > 0 && (
                    <div className="flex flex-wrap gap-2 text-sm text-ink-300">
                      {slotForRealm.missingRequirements.map((requirement) => (
                        <Badge key={`${realm.id}-${requirement}`} variant="default">
                          Missing: {requirement}
                        </Badge>
                      ))}
                    </div>
                  )}
                  {realmTerritories.length > 0 && (
                    <div className="flex items-center gap-2 text-sm text-ink-300">
                      <span>Territories:</span>
                      {realmTerritories.map((t) => (
                        <Badge key={t.id} variant="default">{t.name}</Badge>
                      ))}
                    </div>
                  )}
                  <div className="space-y-2">
                    <span className="text-sm text-ink-300">Technical knowledge</span>
                    <TechnicalKnowledgeBadges
                      knowledge={realm.technicalKnowledge}
                      emptyLabel="No technical knowledge assigned."
                      variant="gold"
                    />
                  </div>
                  {isActive && (
                    <div className="mt-3 space-y-4 border-t border-card-border pt-3">
                      <details className="group">
                        <summary className="cursor-pointer font-heading text-sm font-semibold text-ink-500 select-none">
                          Governance
                        </summary>
                        <div className="mt-3">
                          <GovernanceRealmPanel gameId={gameId} realmId={realm.id} />
                        </div>
                      </details>
                      <details className="group">
                        <summary className="cursor-pointer font-heading text-sm font-semibold text-ink-500 select-none">
                          Troops
                        </summary>
                        <div className="mt-3">
                          <RealmTroopPanel gameId={gameId} realmId={realm.id} settlements={worldSettlements} realmNames={realmMap} />
                        </div>
                      </details>
                      <details className="group">
                        <summary className="cursor-pointer font-heading text-sm font-semibold text-ink-500 select-none">
                          Turmoil Sources
                        </summary>
                        <div className="mt-3 space-y-2">
                          {(realm.turmoilBreakdown ?? []).length === 0 && (
                            <p className="text-ink-300 text-sm">No turmoil sources.</p>
                          )}
                          {(realm.turmoilBreakdown ?? []).map((source) => (
                            <div key={source.id} className="flex items-center justify-between p-2 bg-parchment-100 rounded text-sm">
                              <div className="flex items-center gap-2">
                                <Badge variant={source.amount > 0 ? 'red' : 'green'}>
                                  {source.amount > 0 ? '+' : ''}{source.amount}
                                </Badge>
                                <span>{source.description}</span>
                                <Badge variant="default">
                                  {source.kind === 'gm_manual' ? 'GM' : source.kind.replace(/_/g, ' ')}
                                </Badge>
                                {source.durationType === 'seasonal' && (
                                  <span className="text-ink-300">({source.seasonsRemaining}s left)</span>
                                )}
                              </div>
                              <Button
                                variant="ghost"
                                onClick={() => void removeTurmoilSource(realm.id, source.id)}
                              >
                                Remove
                              </Button>
                            </div>
                          ))}
                          {turmoilForm?.realmId === realm.id ? (
                            <div className="p-3 medieval-border rounded space-y-2">
                              <div className="flex gap-2">
                                <Input
                                  label="Description"
                                  value={turmoilForm.description}
                                  onChange={(e) => setTurmoilForm((f) => f ? { ...f, description: e.target.value } : f)}
                                />
                                <Input
                                  label="Amount"
                                  type="number"
                                  value={String(turmoilForm.amount)}
                                  onChange={(e) => setTurmoilForm((f) => f ? { ...f, amount: Number(e.target.value) || 0 } : f)}
                                />
                              </div>
                              <div className="flex gap-2 items-end">
                                <Select
                                  label="Duration"
                                  options={[
                                    { value: 'permanent', label: 'Permanent' },
                                    { value: 'seasonal', label: 'Seasonal' },
                                  ]}
                                  value={turmoilForm.durationType}
                                  onChange={(e) => setTurmoilForm((f) => f ? { ...f, durationType: e.target.value as 'permanent' | 'seasonal' } : f)}
                                />
                                {turmoilForm.durationType === 'seasonal' && (
                                  <Input
                                    label="Seasons"
                                    type="number"
                                    value={String(turmoilForm.seasonsRemaining)}
                                    onChange={(e) => setTurmoilForm((f) => f ? { ...f, seasonsRemaining: Math.max(1, Number(e.target.value) || 1) } : f)}
                                  />
                                )}
                              </div>
                              <Input
                                label="Notes (optional)"
                                value={turmoilForm.notes}
                                onChange={(e) => setTurmoilForm((f) => f ? { ...f, notes: e.target.value } : f)}
                              />
                              <div className="flex gap-2">
                                <Button variant="accent" onClick={() => void addTurmoilSource()} disabled={savingTurmoil || turmoilForm.amount === 0}>
                                  {savingTurmoil ? 'Adding...' : 'Add Source'}
                                </Button>
                                <Button variant="outline" onClick={() => setTurmoilForm(null)}>Cancel</Button>
                              </div>
                            </div>
                          ) : (
                            <Button
                              variant="outline"
                              onClick={() => setTurmoilForm({
                                realmId: realm.id,
                                description: '',
                                amount: 1,
                                durationType: 'permanent',
                                seasonsRemaining: 1,
                                notes: '',
                              })}
                            >
                              + Add Turmoil Source
                            </Button>
                          )}
                        </div>
                      </details>
                    </div>
                  )}
                </div>
              );
            })}
            {realms.length === 0 && <p className="text-ink-300 text-sm">No realms yet.</p>}
          </div>
        </CardContent>
      </Card>

      {/* World Management */}
      <Card className="mt-6">
        <CardHeader>
          <CardTitle>Territories</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {territories.map((territory) => {
              const isExpanded = expandedTerritory === territory.id;
              const isEditing = editingTerritoryId === territory.id;
              const territorySettlements = worldSettlements.filter((s) => s.territoryId === territory.id);

              return (
                <div key={territory.id} className="medieval-border rounded">
                  <div
                    className="p-3 flex items-center justify-between cursor-pointer hover:bg-parchment-100/50"
                    onClick={() => setExpandedTerritory(isExpanded ? null : territory.id)}
                  >
                    <div className="flex items-center gap-2">
                      <span className={`inline-block text-xs transition-transform ${isExpanded ? 'rotate-90' : ''}`}>&#9654;</span>
                      <span className="font-heading font-semibold">{territory.name}</span>
                      {territory.realmId && <Badge variant="gold">{realmMap[territory.realmId] || 'Unknown'}</Badge>}
                      {!territory.realmId && <Badge variant="default">Neutral</Badge>}
                    </div>
                    <div className="flex items-center gap-2 text-sm text-ink-300">
                      <span>{territorySettlements.length} settlements</span>
                    </div>
                  </div>

                  {isExpanded && (
                    <div className="p-3 pt-0 space-y-4">
                      {/* Territory Edit */}
                      <div className="flex gap-2 items-end">
                        <Button variant="outline" size="sm" onClick={(e) => { e.stopPropagation(); setEditingTerritoryId(isEditing ? null : territory.id); }}>
                          {isEditing ? 'Cancel Edit' : 'Edit Territory'}
                        </Button>
                        <Select
                          label="Owner"
                          options={[{ value: '', label: 'Neutral' }, ...realms.map((r) => ({ value: r.id, label: r.name }))]}
                          value={territory.realmId || ''}
                          onChange={(e) => void assignTerritory(territory.id, e.target.value || null)}
                        />
                      </div>

                      {isEditing && (
                        <div className="p-3 bg-parchment-100/50 rounded space-y-3">
                          <div className="grid grid-cols-2 gap-3">
                            <Input
                              label="Name"
                              value={territory.name}
                              onChange={(e) => {
                                setTerritories((prev) => prev.map((t) => t.id === territory.id ? { ...t, name: e.target.value } : t));
                              }}
                            />
                            <Input
                              label="Food Cap Base"
                              type="number"
                              value={String(territory.foodCapBase)}
                              onChange={(e) => {
                                setTerritories((prev) => prev.map((t) => t.id === territory.id ? { ...t, foodCapBase: Number(e.target.value) || 0 } : t));
                              }}
                            />
                            <Input
                              label="Food Cap Bonus"
                              type="number"
                              value={String(territory.foodCapBonus)}
                              onChange={(e) => {
                                setTerritories((prev) => prev.map((t) => t.id === territory.id ? { ...t, foodCapBonus: Number(e.target.value) || 0 } : t));
                              }}
                            />
                          </div>
                          <div className="flex items-center gap-4">
                            <label className="flex items-center gap-2 text-sm">
                              <input
                                type="checkbox"
                                checked={territory.hasRiverAccess}
                                onChange={(e) => {
                                  setTerritories((prev) => prev.map((t) => t.id === territory.id ? { ...t, hasRiverAccess: e.target.checked } : t));
                                }}
                              />
                              River Access
                            </label>
                            <label className="flex items-center gap-2 text-sm">
                              <input
                                type="checkbox"
                                checked={territory.hasSeaAccess}
                                onChange={(e) => {
                                  setTerritories((prev) => prev.map((t) => t.id === territory.id ? { ...t, hasSeaAccess: e.target.checked } : t));
                                }}
                              />
                              Sea Access
                            </label>
                          </div>
                          <Button variant="accent" size="sm" onClick={() => {
                            void saveTerritory(territory.id, {
                              name: territory.name,
                              foodCapBase: territory.foodCapBase,
                              foodCapBonus: territory.foodCapBonus,
                              hasRiverAccess: territory.hasRiverAccess,
                              hasSeaAccess: territory.hasSeaAccess,
                            });
                            setEditingTerritoryId(null);
                          }}>
                            Save Territory
                          </Button>
                        </div>
                      )}

                      {/* Settlements */}
                      <div>
                        <p className="font-heading text-sm font-semibold text-ink-500 mb-2">Settlements</p>
                        <div className="space-y-2">
                          {territorySettlements.map((settlement) => {
                            const isEditingSett = editingSettlementId === settlement.id;
                            return (
                              <div key={settlement.id} className="p-2 bg-parchment-100/50 rounded space-y-2">
                                <div className="flex items-center justify-between">
                                  <div className="flex items-center gap-2">
                                    <span className="font-semibold">{settlement.name}</span>
                                    <Badge>{settlement.size}</Badge>
                                    {settlement.buildings && <span className="text-xs text-ink-300">{settlement.buildings.length} buildings</span>}
                                  </div>
                                  <div className="flex items-center gap-1">
                                    <Button variant="ghost" size="sm" onClick={() => setEditingSettlementId(isEditingSett ? null : settlement.id)}>
                                      {isEditingSett ? 'Cancel' : 'Edit'}
                                    </Button>
                                    <Button variant="ghost" size="sm" onClick={() => {
                                      if (transferringSettlementId === settlement.id) {
                                        setTransferringSettlementId(null);
                                        setTransferTargetRealmId('');
                                        setTransferTerritory(false);
                                      } else {
                                        setTransferringSettlementId(settlement.id);
                                        setTransferTargetRealmId('');
                                        setTransferTerritory(false);
                                      }
                                    }}>
                                      {transferringSettlementId === settlement.id ? 'Cancel' : 'Transfer'}
                                    </Button>
                                    <Button variant="ghost" size="sm" onClick={() => { if (confirm(`Delete ${settlement.name}?`)) void deleteSettlement(settlement.id); }}>
                                      Delete
                                    </Button>
                                  </div>
                                </div>

                                {isEditingSett && (
                                  <div className="p-2 border border-ink-200 rounded space-y-2">
                                    <div className="grid grid-cols-2 gap-2">
                                      <Input
                                        label="Name"
                                        value={settlement.name}
                                        onChange={(e) => {
                                          setWorldSettlements((prev) => prev.map((s) => s.id === settlement.id ? { ...s, name: e.target.value } : s));
                                        }}
                                      />
                                      <Select
                                        label="Size"
                                        options={SETTLEMENT_SIZE_OPTIONS}
                                        value={settlement.size}
                                        onChange={(e) => {
                                          setWorldSettlements((prev) => prev.map((s) => s.id === settlement.id ? { ...s, size: e.target.value } : s));
                                        }}
                                      />
                                    </div>
                                    <Button variant="accent" size="sm" onClick={() => {
                                      void saveSettlement(settlement.id, {
                                        name: settlement.name,
                                        size: settlement.size,
                                      });
                                    }}>
                                      Save Settlement
                                    </Button>
                                  </div>
                                )}

                                {transferringSettlementId === settlement.id && (
                                  <div className="p-2 border border-gold-500/50 rounded space-y-2 bg-parchment-50/70">
                                    <p className="font-heading text-sm font-semibold">Transfer Settlement</p>
                                    <div className="space-y-2">
                                      <Select
                                        label="Transfer to Realm"
                                        placeholder="Select realm..."
                                        options={realms.filter((r) => r.id !== settlement.realmId).map((r) => ({ value: r.id, label: r.name }))}
                                        value={transferTargetRealmId}
                                        onChange={(e) => setTransferTargetRealmId(e.target.value)}
                                      />
                                      <label className="flex items-center gap-2 text-sm">
                                        <input
                                          type="checkbox"
                                          checked={transferTerritory}
                                          onChange={(e) => setTransferTerritory(e.target.checked)}
                                        />
                                        Also transfer parent territory
                                      </label>
                                      <p className="text-xs text-ink-400">
                                        Adds turmoil to both the losing and gaining realms. Governor will be cleared.
                                      </p>
                                      <Button
                                        variant="accent"
                                        size="sm"
                                        disabled={!transferTargetRealmId}
                                        onClick={() => {
                                          const targetName = realms.find((r) => r.id === transferTargetRealmId)?.name ?? 'selected realm';
                                          if (confirm(`Transfer ${settlement.name} to ${targetName}?`)) {
                                            void transferSettlement(settlement.id);
                                          }
                                        }}
                                      >
                                        Confirm Transfer
                                      </Button>
                                    </div>
                                  </div>
                                )}

                                {/* Buildings */}
                                {settlement.buildings && settlement.buildings.length > 0 && (
                                  <div className="ml-4 space-y-1">
                                    {settlement.buildings.map((building) => (
                                      <div key={building.id} className="flex items-center justify-between text-sm">
                                        <div className="flex items-center gap-2">
                                          <span>{building.type}</span>
                                          <Badge variant="default">{building.size}</Badge>
                                          {!building.isOperational && <Badge variant="gold">Non-operational</Badge>}
                                          {building.constructionTurnsRemaining > 0 && <Badge variant="default">{building.constructionTurnsRemaining} turns left</Badge>}
                                        </div>
                                        <Button variant="ghost" size="sm" onClick={() => { if (confirm(`Delete ${building.type}?`)) void deleteBuilding(building.id); }}>
                                          Delete
                                        </Button>
                                      </div>
                                    ))}
                                  </div>
                                )}
                              </div>
                            );
                          })}
                          {territorySettlements.length === 0 && <p className="text-ink-300 text-sm">No settlements.</p>}
                        </div>
                        {addingSettlement?.territoryId === territory.id ? (
                          <div className="mt-3 space-y-3 rounded border border-ink-200 bg-parchment-50/70 p-3">
                            <div className="grid grid-cols-2 gap-2">
                              <Input
                                label="Name"
                                value={addingSettlement.name}
                                onChange={(e) => setAddingSettlement((prev) => prev ? { ...prev, name: e.target.value } : prev)}
                              />
                              <Select
                                label="Size"
                                options={SETTLEMENT_SIZE_OPTIONS}
                                value={addingSettlement.size}
                                onChange={(e) => setAddingSettlement((prev) => prev ? { ...prev, size: e.target.value } : prev)}
                              />
                            </div>
                            {addingTerritoryMap ? (
                              <div>
                                <p className="text-sm text-ink-400 mb-1">
                                  {addingSettlement.hexId ? 'Hex selected. Click another hex to change.' : 'Click a hex on the map to place the settlement.'}
                                </p>
                                <TerritoryHexMap
                                  data={addingTerritoryMap}
                                  placements={addingSettlement.hexId ? [{ id: 'new', name: addingSettlement.name || 'New', size: addingSettlement.size, hexId: addingSettlement.hexId }] : []}
                                  selectedPlacementId={addingSettlement.hexId ? 'new' : null}
                                  onHexSelect={(hexId) => setAddingSettlement((prev) => prev ? { ...prev, hexId } : prev)}
                                  variant="full"
                                />
                              </div>
                            ) : (
                              <p className="text-sm text-ink-300">Loading territory map...</p>
                            )}
                            <div className="flex gap-2">
                              <Button
                                variant="accent"
                                size="sm"
                                disabled={!addingSettlement.name.trim() || !addingSettlement.hexId}
                                onClick={() => void addSettlement(territory.id, addingSettlement.name, addingSettlement.size, addingSettlement.hexId)}
                              >
                                Create Settlement
                              </Button>
                              <Button variant="outline" size="sm" onClick={() => setAddingSettlement(null)}>
                                Cancel
                              </Button>
                            </div>
                          </div>
                        ) : (
                          <Button
                            variant="outline"
                            size="sm"
                            className="mt-2"
                            onClick={() => setAddingSettlement({ territoryId: territory.id, name: '', size: 'Village', hexId: null })}
                          >
                            + Add Settlement
                          </Button>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
            {territories.length === 0 && <p className="text-ink-300 text-sm">No territories yet.</p>}
          </div>
        </CardContent>
      </Card>

    </main>
  );
}

// ── Governance sub-panel (loaded per realm) ──

interface GovNoble {
  id: string;
  name: string;
  isRuler: boolean;
  isHeir: boolean;
  isActingRuler?: boolean;
  title: string | null;
  officeAssignments: string[];
  isPrisoner: boolean;
  isAlive?: boolean;
  gmStatusText: string | null;
}

interface GovSettlement {
  id: string;
  name: string;
  size: string;
  governingNobleId: string | null;
}

interface GovArmy {
  id: string;
  name: string;
  generalId: string | null;
}

interface GovGOS {
  id: string;
  name: string;
  type: string;
  leaderId: string | null;
}

function GovernanceRealmPanel({ gameId, realmId }: { gameId: string; realmId: string }) {
  const [nobles, setNobles] = useState<GovNoble[]>([]);
  const [settlements, setSettlements] = useState<GovSettlement[]>([]);
  const [armies, setArmies] = useState<GovArmy[]>([]);
  const [gosList, setGosList] = useState<GovGOS[]>([]);
  const [error, setError] = useState('');
  const [loaded, setLoaded] = useState(false);

  const load = useCallback(async () => {
    const [noblesRes, settRes, armiesRes, gosRes] = await Promise.all([
      fetch(`/api/game/${gameId}/nobles?realmId=${realmId}`),
      fetch(`/api/game/${gameId}/settlements?realmId=${realmId}`),
      fetch(`/api/game/${gameId}/armies?realmId=${realmId}`),
      fetch(`/api/game/${gameId}/gos?realmId=${realmId}`),
    ]);
    setNobles(await noblesRes.json());
    setSettlements(await settRes.json());
    const armyData = await armiesRes.json();
    setArmies(armyData.armies ?? armyData);
    setGosList(await gosRes.json());
    setLoaded(true);
  }, [gameId, realmId]);

  useEffect(() => { void load(); }, [load]);

  const currentHeir = nobles.find((n) => n.isHeir);

  async function callAssignEndpoint(url: string, nobleId: string | null): Promise<string | null> {
    setError('');
    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ nobleId }),
    });
    if (!response.ok) {
      const data = await response.json().catch(() => ({}));
      const msg = data.error ?? 'Assignment failed';
      setError(msg);
      return msg;
    }
    await load();
    return null;
  }

  async function assignGovernor(settlementId: string, nobleId: string | null) {
    return callAssignEndpoint(`/api/game/${gameId}/settlements/${settlementId}/governor`, nobleId);
  }

  async function assignGeneral(armyId: string, nobleId: string | null) {
    return callAssignEndpoint(`/api/game/${gameId}/armies/${armyId}/general`, nobleId);
  }

  async function assignLeader(gosId: string, nobleId: string | null) {
    return callAssignEndpoint(`/api/game/${gameId}/gos/${gosId}/leader`, nobleId);
  }

  async function designateHeir(nobleId: string | null) {
    setError('');
    const response = await fetch(`/api/game/${gameId}/governance/heir`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ realmId, nobleId }),
    });
    if (!response.ok) {
      const data = await response.json().catch(() => ({}));
      const msg = data.error ?? 'Failed to designate heir';
      setError(msg);
      return msg;
    }
    await load();
    return null;
  }

  function getOfficeEligibleNobles(currentNobleId: string | null) {
    return nobles.filter((noble) => noble.id === currentNobleId || noble.officeAssignments.length === 0);
  }

  return (
    <div className="space-y-6">
      {error && <p className="text-sm text-red-500">{error}</p>}

      {!loaded ? (
        <Button variant="outline" size="sm" onClick={() => void load()}>Load Governance</Button>
      ) : (
        <>
          {/* Heir */}
          <div>
            <p className="font-heading font-semibold text-sm mb-2">Heir Designation</p>
            <NobleAssignmentSelect
              label="Heir"
              nobles={nobles.filter((n) => !n.isRuler && n.isAlive !== false && !n.isPrisoner)}
              currentNobleId={currentHeir?.id ?? null}
              onAssign={designateHeir}
            />
          </div>

          {/* Settlements — Governors */}
          {settlements.length > 0 && (
            <div>
              <p className="font-heading font-semibold text-sm mb-2">Settlement Governors</p>
              <div className="space-y-3">
                {settlements.map((s) => (
                  <NobleAssignmentSelect
                    key={s.id}
                    label={`${s.name} (${s.size})`}
                    nobles={getOfficeEligibleNobles(s.governingNobleId)}
                    currentNobleId={s.governingNobleId}
                    onAssign={(nobleId) => assignGovernor(s.id, nobleId)}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Armies — Generals */}
          {armies.length > 0 && (
            <div>
              <p className="font-heading font-semibold text-sm mb-2">Army Generals</p>
              <div className="space-y-3">
                {armies.map((a) => (
                  <NobleAssignmentSelect
                    key={a.id}
                    label={a.name}
                    nobles={getOfficeEligibleNobles(a.generalId)}
                    currentNobleId={a.generalId}
                    onAssign={(nobleId) => assignGeneral(a.id, nobleId)}
                  />
                ))}
              </div>
            </div>
          )}

          {/* GOS — Leaders */}
          {gosList.length > 0 && (
            <div>
              <p className="font-heading font-semibold text-sm mb-2">Guild / Order / Society Leaders</p>
              <div className="space-y-3">
                {gosList.map((g) => (
                  <NobleAssignmentSelect
                    key={g.id}
                    label={`${g.name} (${g.type})`}
                    nobles={getOfficeEligibleNobles(g.leaderId)}
                    currentNobleId={g.leaderId}
                    onAssign={(nobleId) => assignLeader(g.id, nobleId)}
                  />
                ))}
              </div>
            </div>
          )}

          {/* Noble status text */}
          <div>
            <p className="font-heading font-semibold text-sm mb-2">Noble Status & Activity</p>
            <div className="space-y-3">
              {nobles.map((noble) => (
                <div key={noble.id} className="p-3 medieval-border rounded space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-heading font-bold">{noble.name}</span>
                    <NobleActivityBadge noble={noble} />
                  </div>
                  <NobleStatusEditor
                    gameId={gameId}
                    nobleId={noble.id}
                    nobleName={noble.name}
                    initialText={noble.gmStatusText}
                    onSaved={(text) => {
                      setNobles((prev) => prev.map((n) => n.id === noble.id ? { ...n, gmStatusText: text } : n));
                    }}
                  />
                </div>
              ))}
              {nobles.length === 0 && <p className="text-ink-300 text-sm">No nobles in this realm.</p>}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// ── Troop sub-panel (loaded per realm) ──

function RealmTroopPanel({ gameId, realmId, settlements: allSettlements, realmNames }: { gameId: string; realmId: string; settlements: Settlement[]; realmNames: Record<string, string> }) {
  const [troops, setTroops] = useState<Troop[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState('');
  const [transfer, setTransfer] = useState<{ troopIds: string[]; targetSettlementId: string }>({ troopIds: [], targetSettlementId: '' });

  async function load() {
    const response = await fetch(`/api/game/${gameId}/troops?realmId=${realmId}`, { cache: 'no-store' });
    if (response.ok) {
      setTroops(await response.json());
    }
    setLoaded(true);
  }

  async function transferTroops() {
    if (transfer.troopIds.length === 0 || !transfer.targetSettlementId) return;
    setError('');
    const response = await fetch(`/api/game/${gameId}/troops`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ troopIds: transfer.troopIds, garrisonSettlementId: transfer.targetSettlementId }),
    });
    if (!response.ok) {
      const data = await response.json().catch(() => ({}));
      setError(data.error ?? 'Failed to transfer troops');
      return;
    }
    setTransfer({ troopIds: [], targetSettlementId: '' });
    await load();
  }

  if (!loaded) {
    return <Button variant="outline" size="sm" onClick={() => void load()}>Load Troops</Button>;
  }

  const settlementMap = Object.fromEntries(allSettlements.map((s) => [s.id, s.name]));
  const grouped = new Map<string, Troop[]>();
  for (const troop of troops) {
    const key = troop.garrisonSettlementId || troop.armyId || 'unassigned';
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push(troop);
  }

  return (
    <div className="space-y-3">
      {error && <p className="text-sm text-red-500">{error}</p>}
      {troops.length === 0 && <p className="text-ink-300 text-sm">No troops.</p>}
      {Array.from(grouped.entries()).map(([key, groupTroops]) => {
        const locationName = settlementMap[key] || (key === 'unassigned' ? 'Unassigned' : `Army ${key.slice(0, 8)}`);
        const allSelected = groupTroops.every((t) => transfer.troopIds.includes(t.id));

        return (
          <div key={key} className="p-3 medieval-border rounded space-y-2">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="font-heading font-semibold">{locationName}</span>
                <Badge>{groupTroops.length} troops</Badge>
              </div>
              <Button variant="ghost" size="sm" onClick={() => {
                if (allSelected) {
                  setTransfer((prev) => ({ ...prev, troopIds: prev.troopIds.filter((id) => !groupTroops.some((t) => t.id === id)) }));
                } else {
                  setTransfer((prev) => ({ ...prev, troopIds: [...new Set([...prev.troopIds, ...groupTroops.map((t) => t.id)])] }));
                }
              }}>
                {allSelected ? 'Deselect All' : 'Select All'}
              </Button>
            </div>
            <div className="space-y-1 ml-4">
              {groupTroops.map((troop) => (
                <label key={troop.id} className="flex items-center gap-2 text-sm">
                  <input
                    type="checkbox"
                    checked={transfer.troopIds.includes(troop.id)}
                    onChange={(e) => {
                      if (e.target.checked) {
                        setTransfer((prev) => ({ ...prev, troopIds: [...prev.troopIds, troop.id] }));
                      } else {
                        setTransfer((prev) => ({ ...prev, troopIds: prev.troopIds.filter((id) => id !== troop.id) }));
                      }
                    }}
                  />
                  <span>{troop.type}</span>
                  <Badge variant="default">{troop.class}</Badge>
                  <Badge variant="default">{troop.armourType}</Badge>
                </label>
              ))}
            </div>
          </div>
        );
      })}

      {transfer.troopIds.length > 0 && (
        <div className="flex gap-3 items-end p-3 bg-parchment-100/50 rounded">
          <div className="flex flex-col gap-1.5">
            <label className="font-heading text-sm font-medium text-ink-500">
              Transfer {transfer.troopIds.length} troop(s) to
            </label>
            <select
              className="w-full px-4 py-2.5 bg-input-bg border-2 border-input-border rounded text-foreground focus:outline-none focus:border-accent transition-colors cursor-pointer"
              value={transfer.targetSettlementId}
              onChange={(e) => setTransfer((prev) => ({ ...prev, targetSettlementId: e.target.value }))}
            >
              <option value="">Select garrison...</option>
              {(() => {
                const thisRealm = allSettlements.filter((s) => s.realmId === realmId);
                const otherRealms = new Map<string, Settlement[]>();
                for (const s of allSettlements) {
                  if (s.realmId === realmId || !s.realmId) continue;
                  if (!otherRealms.has(s.realmId)) otherRealms.set(s.realmId, []);
                  otherRealms.get(s.realmId)!.push(s);
                }
                return (
                  <>
                    <optgroup label={realmNames[realmId] || 'This Realm'}>
                      {thisRealm.map((s) => (
                        <option key={s.id} value={s.id}>{s.name} ({s.size})</option>
                      ))}
                    </optgroup>
                    {Array.from(otherRealms.entries()).map(([rId, settlements]) => (
                      <optgroup key={rId} label={realmNames[rId] || rId}>
                        {settlements.map((s) => (
                          <option key={s.id} value={s.id}>{s.name} ({s.size})</option>
                        ))}
                      </optgroup>
                    ))}
                  </>
                );
              })()}
            </select>
          </div>
          <Button variant="accent" onClick={() => void transferTroops()} disabled={!transfer.targetSettlementId}>
            Transfer
          </Button>
        </div>
      )}
    </div>
  );
}
