import type { TurmoilSource } from '@/types/game';
import type { FoodBalanceInput } from '@/lib/game-logic/food';
import type { ProductSource } from '@/lib/game-logic/trade';
import type { DicePoolTroop } from '@/lib/game-logic/combat';

export function createTurmoilSource(overrides?: Partial<TurmoilSource>): TurmoilSource {
  return {
    id: 'ts-1',
    kind: 'gm_event',
    description: 'Test turmoil',
    amount: 2,
    durationType: 'seasonal',
    seasonsRemaining: 2,
    originYear: 1,
    originSeason: 'Spring',
    autoGenerated: true,
    notes: null,
    ...overrides,
  };
}

export function createFoodBalanceInput(overrides?: Partial<FoodBalanceInput>): FoodBalanceInput {
  return {
    settlements: [{ size: 'Village', occupiedSlots: 2, totalSlots: 4 }],
    standaloneForts: 0,
    standaloneCastles: 0,
    ...overrides,
  };
}

export function createProductSource(
  overrides?: Partial<ProductSource> & { qualityTier?: number },
): ProductSource {
  const { qualityTier, ...rest } = overrides ?? {};

  return {
    realmId: 'r-1',
    routeId: 'route-1',
    settlementId: 'settlement-1',
    resourceType: 'Ore',
    qualityTier: qualityTier ?? 1,
    taxType: 'Tribute',
    ...rest,
  };
}

export function createDicePoolTroop(overrides?: Partial<DicePoolTroop>): DicePoolTroop {
  return {
    class: 'Basic',
    count: 3,
    ...overrides,
  };
}
