import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { v4 as uuid } from 'uuid';
import { db } from '@/db';
import { games, realms } from '@/db/schema';
import { isAuthError, requireGM } from '@/lib/auth';
import { parseJson } from '@/lib/json';
import type { Season, TurmoilSource } from '@/types/game';

/**
 * POST: Add a GM manual turmoil source to a realm
 * Body: { realmId, description, amount, durationType?, seasonsRemaining?, notes? }
 */
export async function POST(
  request: Request,
  { params }: { params: Promise<{ gameId: string }> },
) {
  try {
    const { gameId } = await params;
    await requireGM(gameId);

    const body = await request.json();
    const { realmId, description, amount, durationType, seasonsRemaining, notes } = body;

    if (!realmId || typeof amount !== 'number' || !Number.isFinite(amount) || amount === 0) {
      return NextResponse.json({ error: 'realmId and non-zero numeric amount required' }, { status: 400 });
    }

    const game = await db.select().from(games).where(eq(games.id, gameId)).get();
    if (!game) {
      return NextResponse.json({ error: 'Game not found' }, { status: 404 });
    }

    const realm = await db.select().from(realms)
      .where(and(eq(realms.id, realmId), eq(realms.gameId, gameId)))
      .get();
    if (!realm) {
      return NextResponse.json({ error: 'Realm not found' }, { status: 404 });
    }

    const source: TurmoilSource = {
      id: `gm-manual:${uuid()}`,
      kind: 'gm_manual',
      description: (description?.trim() as string) || 'GM adjustment',
      amount: Math.trunc(amount),
      durationType: durationType === 'seasonal' ? 'seasonal' : 'permanent',
      seasonsRemaining: durationType === 'seasonal'
        ? Math.max(1, Math.trunc(seasonsRemaining ?? 1))
        : undefined,
      originYear: game.currentYear,
      originSeason: game.currentSeason as Season,
      autoGenerated: false,
      notes: notes ?? null,
    };

    const storedSources = parseJson<TurmoilSource[]>(realm.turmoilSources, []);
    const updatedSources = [...storedSources, source];

    await db.update(realms)
      .set({ turmoilSources: JSON.stringify(updatedSources) })
      .where(eq(realms.id, realmId));

    return NextResponse.json({ source, turmoilSources: updatedSources });
  } catch (error) {
    if (isAuthError(error)) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    throw error;
  }
}

/**
 * DELETE: Remove a turmoil source from a realm by source ID
 * Body: { realmId, sourceId }
 */
export async function DELETE(
  request: Request,
  { params }: { params: Promise<{ gameId: string }> },
) {
  try {
    const { gameId } = await params;
    await requireGM(gameId);

    const body = await request.json();
    const { realmId, sourceId } = body;

    if (!realmId || !sourceId) {
      return NextResponse.json({ error: 'realmId and sourceId required' }, { status: 400 });
    }

    const realm = await db.select().from(realms)
      .where(and(eq(realms.id, realmId), eq(realms.gameId, gameId)))
      .get();
    if (!realm) {
      return NextResponse.json({ error: 'Realm not found' }, { status: 404 });
    }

    const storedSources = parseJson<TurmoilSource[]>(realm.turmoilSources, []);
    const updatedSources = storedSources.filter((s) => s.id !== sourceId);

    if (updatedSources.length === storedSources.length) {
      return NextResponse.json({ error: 'Source not found' }, { status: 404 });
    }

    await db.update(realms)
      .set({ turmoilSources: JSON.stringify(updatedSources) })
      .where(eq(realms.id, realmId));

    return NextResponse.json({ removed: sourceId, turmoilSources: updatedSources });
  } catch (error) {
    if (isAuthError(error)) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    throw error;
  }
}
