import type {
  GameInitState,
  GamePhase,
  GMSetupState,
  BuildingLocationType,
  BuildingMaintenanceState,
  GovernanceState,
  GovernmentType,
  PlayerSetupState,
  ResourceRarity,
  ResourceType,
  Season,
  SettlementKind,
  SettlementSize,
  TaxType,
  TechnicalKnowledgeKey,
  TurnPhase,
} from '@/types/game';
import type { PlayerSetupChecklist } from '@/lib/game-init-state';

export interface GameDto {
  id: string;
  name: string;
  gamePhase: GamePhase;
  initState: GameInitState;
  gmSetupState: GMSetupState;
  currentYear: number;
  currentSeason: Season;
  turnPhase: TurnPhase;
  createdAt?: string | number | Date | null;
  gmCode?: string;
}

export interface TurmoilSourceDto {
  id: string;
  kind: string;
  description: string;
  amount: number;
  durationType: 'permanent' | 'seasonal';
  seasonsRemaining?: number;
  autoGenerated: boolean;
}

export interface RealmResponseDto {
  id: string;
  gameId?: string;
  name: string;
  governmentType: GovernmentType;
  governanceState?: GovernanceState;
  traditions: string;
  isNPC?: boolean;
  treasury: number;
  taxType: TaxType;
  technicalKnowledge: string;
  capitalSettlementId?: string | null;
  projectedTurmoil?: number | null;
  buildingTurmoilReduction?: number | null;
  turmoilBreakdown?: TurmoilSourceDto[];
  openTurmoilEventId?: string | null;
  winterUnrestPending?: boolean;
  color?: string | null;
}

export interface RealmDto extends Omit<RealmResponseDto, 'technicalKnowledge'> {
  technicalKnowledge: TechnicalKnowledgeKey[];
}

export interface GameTerritoryDto {
  id: string;
  gameId?: string;
  name: string;
  realmId: string | null;
  description: string | null;
  foodCapBase: number;
  foodCapBonus: number;
  hasRiverAccess: boolean;
  hasSeaAccess: boolean;
}

export interface SettlementBuildingDto {
  id: string;
  settlementId: string | null;
  territoryId: string | null;
  hexId?: string | null;
  locationType?: BuildingLocationType;
  type: string;
  category: string;
  size: string;
  material: string | null;
  takesBuildingSlot?: boolean;
  isOperational: boolean;
  maintenanceState?: BuildingMaintenanceState;
  constructionTurnsRemaining: number;
  ownerGosId?: string | null;
  allottedGosId?: string | null;
}

export interface GameSettlementDto {
  id: string;
  territoryId: string;
  hexId: string | null;
  realmId: string | null;
  name: string;
  kind: SettlementKind;
  size: SettlementSize;
  isCapital?: boolean;
  governingNobleId?: string | null;
  ownerGosId?: string | null;
  governingNoble?: {
    id: string;
    name: string;
    gmStatusText: string | null;
  } | null;
  buildings?: SettlementBuildingDto[];
  territoryBuildings?: SettlementBuildingDto[];
}

export interface ResourceSiteDto {
  id: string;
  territoryId: string;
  settlementId: string | null;
  resourceType: ResourceType;
  rarity: ResourceRarity;
  industryCapacity?: number;
  ownerGosId?: string | null;
}

export interface PlayerSlotDto {
  id: string;
  claimCode: string;
  territoryId: string;
  territoryName: string | null;
  realmId: string | null;
  realmName: string | null;
  displayName: string | null;
  setupState: PlayerSetupState;
  status: 'claimed' | 'unclaimed';
  checklist: PlayerSetupChecklist | null;
  missingRequirements: string[];
}
