import { NextResponse } from 'next/server';
import { db } from '@/db';
import { turnEvents } from '@/db/schema';
import { eq, desc } from 'drizzle-orm';
import { v4 as uuid } from 'uuid';
import { isAuthError, requireGM } from '@/lib/auth';
import { normalizeEconomicModifiers } from '@/lib/game-logic/economic-modifiers';
import type { Season, TurnEventKind, TurnEventStatus } from '@/types/game';

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ gameId: string }> }
) {
  const { gameId } = await params;
  const list = await db.select().from(turnEvents)
    .where(eq(turnEvents.gameId, gameId))
    .orderBy(desc(turnEvents.year), desc(turnEvents.season));
  return NextResponse.json(list);
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ gameId: string }> }
) {
  try {
    const { gameId } = await params;
    await requireGM(gameId);
    const body = await request.json();

    if (body.eventType) {
      return NextResponse.json(
        { error: 'Governance events must use /api/game/:gameId/governance/events' },
        { status: 400 },
      );
    }

    const id = uuid();
    const kind = (body.kind ?? 'gm_event') as TurnEventKind;
    const status = (body.status ?? 'open') as TurnEventStatus;
    const modifiers = normalizeEconomicModifiers(body.modifiers ?? body.mechanicalEffect, {
      description: body.description,
      idPrefix: id,
      originYear: body.year,
      originSeason: body.season as Season,
      linkedEntityType: 'event',
      linkedEntityId: id,
      autoGenerated: body.autoGenerated ?? false,
    });
    const mechanicalEffect =
      modifiers.length > 0
        ? JSON.stringify(modifiers)
        : typeof body.mechanicalEffect === 'string'
          ? body.mechanicalEffect
          : null;
    const payload = typeof body.payload === 'object' && body.payload !== null ? body.payload : {};

    await db.insert(turnEvents).values({
      id,
      gameId,
      year: body.year,
      season: body.season,
      realmId: body.realmId || null,
      kind,
      status,
      title: body.title ?? null,
      description: body.description,
      payload: JSON.stringify(payload),
      mechanicalEffect,
      resolution: body.resolution ?? null,
      autoGenerated: body.autoGenerated ?? false,
      resolvedAt: null,
      resolvedBy: null,
    });

    return NextResponse.json({
      id,
      gameId,
      year: body.year,
      season: body.season,
      realmId: body.realmId || null,
      kind,
      status,
      title: body.title ?? null,
      description: body.description,
      payload,
      mechanicalEffect,
      resolution: body.resolution ?? null,
      autoGenerated: body.autoGenerated ?? false,
      resolvedAt: null,
      resolvedBy: null,
    });
  } catch (error) {
    if (isAuthError(error)) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }

    throw error;
  }
}
