import { apiErrorResponse } from '@/lib/api-errors';
import { NextResponse } from 'next/server';
import { requireGM } from '@/lib/auth';
import { normalizeEconomicModifiers } from '@/lib/game-logic/economic-modifiers';
import { createEvent, getEventsForRealm } from '@/lib/turn-event-service';
import type { Season, TurnEventKind, TurnEventStatus } from '@/types/game';

export async function GET(
  request: Request,
  { params }: { params: Promise<{ gameId: string }> }
) {
  const { gameId } = await params;
  const url = new URL(request.url);
  const realmId = url.searchParams.get('realmId');
  const yearParam = url.searchParams.get('year');
  const season = url.searchParams.get('season') as Season | null;
  if (!realmId) {
    return NextResponse.json({ error: 'realmId required' }, { status: 400 });
  }
  return NextResponse.json(getEventsForRealm(
    gameId,
    realmId,
    yearParam ? Number(yearParam) : undefined,
    season ?? undefined,
  ));
}

export async function POST(
  request: Request,
  { params }: { params: Promise<{ gameId: string }> }
) {
  try {
    const { gameId } = await params;
    await requireGM(gameId);
    const body = await request.json();

    if (body.eventType) {
      return NextResponse.json(
        { error: 'Governance events must use /api/game/:gameId/governance/events' },
        { status: 400 },
      );
    }

    const kind = (body.kind ?? 'gm_event') as TurnEventKind;
    const status = (body.status ?? 'open') as TurnEventStatus;
    const payload = typeof body.payload === 'object' && body.payload !== null ? body.payload : {};
    const audienceRealmIds = Array.isArray(body.audienceRealmIds)
      ? body.audienceRealmIds
      : body.realmId ? [body.realmId] : [];
    const modifiers = normalizeEconomicModifiers(body.modifiers ?? body.mechanicalEffect, {
      description: body.description,
      idPrefix: crypto.randomUUID(),
      originYear: body.year,
      originSeason: body.season as Season,
      linkedEntityType: 'event',
      autoGenerated: body.autoGenerated ?? false,
    });

    const event = createEvent({
      gameId,
      year: body.year,
      season: body.season,
      kind,
      status,
      audienceRealmIds,
      actionId: body.actionId ?? null,
      causedByRealmId: body.causedByRealmId ?? null,
      outcome: body.outcome ?? null,
      rolls: Array.isArray(body.rolls) ? body.rolls : [],
      abilityUsed: body.abilityUsed ?? null,
      abilityModifier: Number.isInteger(body.abilityModifier) ? body.abilityModifier : null,
      nobleId: body.nobleId ?? null,
      title: body.title ?? null,
      description: body.description,
      payload,
      mechanicalEffect: modifiers.length > 0
        ? JSON.stringify(modifiers)
        : typeof body.mechanicalEffect === 'string' ? body.mechanicalEffect : null,
      resolution: body.resolution ?? null,
      autoGenerated: body.autoGenerated ?? false,
    });

    return NextResponse.json(event);
  } catch (error) {
    const errorResponse = apiErrorResponse(error);
    if (errorResponse) return errorResponse;
    throw error;
  }
}
