import { v4 as uuid } from 'uuid';
import { TAX_TURMOIL } from '@/lib/game-logic/constants';
import type {
  Season,
  TaxType,
  TurnEventKind,
  TurnEventStatus,
  TurmoilReviewPayload,
  TurmoilSource,
  WinterUnrestLocationOption,
  WinterUnrestPayload,
} from '@/types/game';

export interface RealmTurmoilSourceInput {
  storedSources: TurmoilSource[];
  nobleSources?: TurmoilSource[];
  gosSources?: TurmoilSource[];
  eventSources?: TurmoilSource[];
}

export interface TurmoilEventDraft {
  id: string;
  gameId: string;
  year: number;
  season: Season;
  realmId: string;
  kind: TurnEventKind;
  status: TurnEventStatus;
  title: string;
  description: string;
  payload: string;
  mechanicalEffect: string | null;
  resolution: string | null;
  autoGenerated: boolean;
  resolvedAt: null;
  resolvedBy: null;
}

export interface WinterUnrestRoll {
  unrestKind: WinterUnrestPayload['unrestKind'];
}

export function calculateDerivedTurmoil(
  taxType: TaxType,
  sources: TurmoilSource[],
  buildingReduction: number,
) {
  const baseTurmoil = TAX_TURMOIL[taxType];
  const sourceTurmoil = sources.reduce((sum, source) => sum + source.amount, 0);
  return Math.max(0, baseTurmoil + sourceTurmoil - buildingReduction);
}

export function advanceTurmoilSources(sources: TurmoilSource[]) {
  return sources
    .map((source) => {
      if (source.durationType === 'permanent') {
        return source;
      }

      return {
        ...source,
        seasonsRemaining: (source.seasonsRemaining ?? 0) - 1,
      };
    })
    .filter((source) => source.durationType === 'permanent' || (source.seasonsRemaining ?? 0) > 0);
}

export function buildRealmTurmoilSources(input: RealmTurmoilSourceInput) {
  const merged = [
    ...input.storedSources,
    ...(input.nobleSources ?? []),
    ...(input.gosSources ?? []),
    ...(input.eventSources ?? []),
  ];

  const byId = new Map<string, TurmoilSource>();
  for (const source of merged) {
    byId.set(source.id, source);
  }

  return [...byId.values()];
}

export function rollWinterUnrest(turmoil: number): WinterUnrestRoll {
  if (turmoil >= 9) {
    return { unrestKind: 'revolt' };
  }

  if (turmoil >= 5) {
    return { unrestKind: 'riot' };
  }

  return { unrestKind: 'protest' };
}

export function createTurmoilReviewEventDraft(args: {
  gameId: string;
  year: number;
  season: Season;
  realmId: string;
  realmName: string;
  projectedTurmoil: number;
  buildingReduction: number;
  turmoilBreakdown: TurmoilSource[];
}) {
  const payload: TurmoilReviewPayload = {
    realmId: args.realmId,
    projectedTurmoil: args.projectedTurmoil,
    buildingReduction: args.buildingReduction,
    turmoilBreakdown: args.turmoilBreakdown,
    manualSources: [],
    gmNotes: null,
  };

  return {
    id: uuid(),
    gameId: args.gameId,
    year: args.year,
    season: args.season,
    realmId: args.realmId,
    kind: 'turmoil_review' as const,
    status: 'open' as const,
    title: `Turmoil review: ${args.realmName}`,
    description: `${args.realmName} enters ${args.season} Y${args.year} with ${args.projectedTurmoil} derived turmoil.`,
    payload: JSON.stringify(payload),
    mechanicalEffect: null,
    resolution: null,
    autoGenerated: true,
    resolvedAt: null,
    resolvedBy: null,
  } satisfies TurmoilEventDraft;
}

export function createWinterUnrestEventDraft(args: {
  gameId: string;
  year: number;
  season: Season;
  realmId: string;
  realmName: string;
  projectedTurmoil: number;
  turmoilBreakdown: TurmoilSource[];
  locationOptions: WinterUnrestLocationOption[];
}) {
  const roll = rollWinterUnrest(args.projectedTurmoil);
  const payload: WinterUnrestPayload = {
    realmId: args.realmId,
    turmoil: args.projectedTurmoil,
    turmoilSources: args.turmoilBreakdown,
    unrestKind: roll.unrestKind,
    locationOptions: args.locationOptions,
    selectedSettlementId: null,
    gmNotes: null,
    manualSources: [],
  };

  return {
    id: uuid(),
    gameId: args.gameId,
    year: args.year,
    season: args.season,
    realmId: args.realmId,
    kind: 'winter_unrest' as const,
    status: 'open' as const,
    title: `Winter unrest: ${args.realmName}`,
    description: `${args.realmName} faces ${roll.unrestKind} risk in Winter Y${args.year}.`,
    payload: JSON.stringify(payload),
    mechanicalEffect: null,
    resolution: null,
    autoGenerated: true,
    resolvedAt: null,
    resolvedBy: null,
  } satisfies TurmoilEventDraft;
}
