import { apiErrorResponse } from '@/lib/api-errors';
import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { db } from '@/db';
import { realms, turnEvents } from '@/db/schema';
import { requireGM } from '@/lib/auth';
import { parseJson } from '@/lib/json';
import type { Season, TurnEventStatus, TurmoilSource } from '@/types/game';

function normalizeManualTurmoilSources(
  raw: unknown,
  eventId: string,
  year: number,
  season: Season,
): TurmoilSource[] {
  if (!Array.isArray(raw)) {
    return [];
  }

  return raw.flatMap((item, index) => {
    if (!item || typeof item !== 'object') {
      return [];
    }

    const candidate = item as Partial<TurmoilSource>;
    if (typeof candidate.amount !== 'number' || !Number.isFinite(candidate.amount)) {
      return [];
    }

    return [{
      id: candidate.id ?? `${eventId}:manual:${index + 1}`,
      kind: 'gm_manual' as const,
      description: candidate.description?.trim() || 'Manual turmoil source',
      amount: Math.trunc(candidate.amount),
      durationType: candidate.durationType === 'seasonal' ? 'seasonal' : 'permanent',
      seasonsRemaining: candidate.durationType === 'seasonal'
        ? Math.max(1, Math.trunc(candidate.seasonsRemaining ?? 1))
        : undefined,
      originYear: candidate.originYear ?? year,
      originSeason: candidate.originSeason ?? season,
      linkedEntityType: 'event',
      linkedEntityId: eventId,
      autoGenerated: false,
      notes: candidate.notes ?? null,
    }];
  });
}

export async function PATCH(
  request: Request,
  { params }: { params: Promise<{ gameId: string; eventId: string }> },
) {
  try {
    const { gameId, eventId } = await params;
    await requireGM(gameId);

    const event = await db.select().from(turnEvents).where(and(
      eq(turnEvents.id, eventId),
      eq(turnEvents.gameId, gameId),
    )).get();

    if (!event) {
      return NextResponse.json({ error: 'Event not found' }, { status: 404 });
    }

    const body = await request.json();
    const payload = parseJson<Record<string, unknown>>(event.payload, {});
    const updates: Record<string, unknown> = {};

    if (body.title !== undefined) {
      updates.title = body.title;
    }

    if (body.description !== undefined) {
      updates.description = body.description;
    }

    if (body.resolution !== undefined) {
      updates.resolution = body.resolution;
    }

    if (body.payload && typeof body.payload === 'object') {
      Object.assign(payload, body.payload);
    }

    if (body.selectedSettlementId !== undefined) {
      payload.selectedSettlementId = body.selectedSettlementId;
    }

    if (body.gmNotes !== undefined) {
      payload.gmNotes = body.gmNotes;
    }

    const manualSources = normalizeManualTurmoilSources(
      body.manualTurmoilSources,
      eventId,
      event.year,
      event.season as Season,
    );

    if (manualSources.length > 0) {
      payload.manualSources = [
        ...((payload.manualSources as TurmoilSource[] | undefined) ?? []),
        ...manualSources,
      ];

      if (event.realmId) {
        const realm = await db.select().from(realms).where(eq(realms.id, event.realmId)).get();
        if (realm) {
          const storedSources = parseJson<TurmoilSource[]>(realm.turmoilSources, []);
          await db.update(realms)
            .set({ turmoilSources: JSON.stringify([...storedSources, ...manualSources]) })
            .where(eq(realms.id, realm.id));
        }
      }
    }

    if (body.status !== undefined) {
      updates.status = body.status as TurnEventStatus;
      if (body.status === 'resolved' || body.status === 'dismissed') {
        updates.resolvedAt = new Date();
        updates.resolvedBy = 'gm';
      } else {
        updates.resolvedAt = null;
        updates.resolvedBy = null;
      }
    }

    updates.payload = JSON.stringify(payload);

    await db.update(turnEvents)
      .set(updates)
      .where(and(
        eq(turnEvents.id, eventId),
        eq(turnEvents.gameId, gameId),
      ));

    return NextResponse.json({
      ...event,
      ...updates,
      payload,
    });
  } catch (error) {
    const errorResponse = apiErrorResponse(error);
    if (errorResponse) return errorResponse;
    throw error;
  }
}
